import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedRegist/Generated123456deverdadWidget.dart';
import 'package:flutterapp/ui/widgets/generatedRegist/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/ui/widgets/generatedRegist/GeneratedClaveWidget.dart';

/* Frame Group 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -0.8695654273033142,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.86956024169922,
              child: GeneratedRectangle4Widget4(),
            ),
            Positioned(
              left: 24.0,
              top: -13.043477058410645,
              right: null,
              bottom: null,
              width: 55.0,
              height: 18.043477058410645,
              child: GeneratedClaveWidget(),
            ),
            Positioned(
              left: 14.0,
              top: 12.173913955688477,
              right: null,
              bottom: null,
              width: 225.0,
              height: 15.91303825378418,
              child: Generated123456deverdadWidget(),
            )
          ]),
    );
  }
}
