import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedRegist/GeneratedNombreWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedRegist/GeneratedRectangle4Widget5.dart';
import 'package:flutterapp/ui/widgets/generatedRegist/GeneratedNombreoaliasWidget.dart';

/* Frame Group 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -0.9230942726135254,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.61539077758789,
              child: GeneratedRectangle4Widget5(),
            ),
            Positioned(
              left: 19.0,
              top: -12.173914909362793,
              right: null,
              bottom: null,
              width: 78.54217529296875,
              height: 17.92307758331299,
              child: GeneratedNombreWidget1(),
            ),
            Positioned(
              left: 14.0,
              top: 12.173914909362793,
              right: null,
              bottom: null,
              width: 225.0,
              height: 15.913046836853027,
              child: GeneratedNombreoaliasWidget(),
            )
          ]),
    );
  }
}
