import 'package:flutter/material.dart';

/* Text New York Times
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewYorkTimesWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.bottomLeft,
      child: Text(
        '''New York Times''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 2.125,
          fontSize: 12.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 120, 133, 143),

          /* letterSpacing: 0.5, */
        ),
      ),
    );
  }
}
