import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedImageWidget4.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedRectangle1950Widget4.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedMediacontentWidget4.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedIconWidget4.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 149.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 149.0,
              child: GeneratedRectangle1950Widget4(),
            ),
            Positioned(
              left: 211.0,
              top: 14.385320663452148,
              right: null,
              bottom: null,
              width: 100.0,
              height: 89.90825653076172,
              child: GeneratedImageWidget4(),
            ),
            Positioned(
              left: 11.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 189.0,
              height: 66.73394775390625,
              child:
                  GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget2(),
            ),
            Positioned(
              left: 15.0,
              top: 97.0,
              right: null,
              bottom: null,
              width: 101.0,
              height: 38.0,
              child: GeneratedMediacontentWidget4(),
            ),
            Positioned(
              left: 287.0,
              top: 107.0,
              right: null,
              bottom: null,
              width: 19.606779098510742,
              height: 24.0,
              child: GeneratedIconWidget4(),
            )
          ]),
    );
  }
}
