import 'package:flutter/material.dart';

/* Text See All
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSeeAllWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Ver más''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Calibri',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
