import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedArteWidget.dart';

/* Frame Frame 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 71.0,
      height: 25.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(20.0),
              child: Container(
                color: Color.fromARGB(255, 125, 204, 228),
              ),
            ),
            Positioned(
              left: 23.0,
              top: 4.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 22.0,
              child: GeneratedArteWidget(),
            )
          ]),
    );
  }
}
