import 'package:flutter/material.dart';

/* Rectangle Fire
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFireWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 30.0,
      height: 30.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/7ad09d387450a91951c6ec0c831a722ef8bee4e1.png",
          color: null,
          fit: BoxFit.contain,
          width: 30.0,
          height: 30.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
