import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedFrame73Widget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedFrame1Widget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedFrame7Widget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedFrame72Widget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedFrame2Widget.dart';

/* Frame Frame 74
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame74Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 490.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 322.0,
                    height: 18.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 1.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 25.0,
                            child: GeneratedFrame1Widget(),
                          ),
                          Positioned(
                            left: 111.0,
                            top: 1.0,
                            right: null,
                            bottom: null,
                            width: 71.0,
                            height: 25.0,
                            child: GeneratedFrame2Widget(),
                          ),
                          Positioned(
                            left: 194.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 71.0,
                            height: 25.0,
                            child: GeneratedFrame7Widget(),
                          ),
                          Positioned(
                            left: 276.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 25.0,
                            child: GeneratedFrame72Widget(),
                          ),
                          Positioned(
                            left: 393.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 97.0,
                            height: 25.0,
                            child: GeneratedFrame73Widget(),
                          )
                        ]),
                  ))
            ])),
      );
    });
  }
}
