import 'package:flutter/material.dart';

/* Text Artículos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArtculosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Artículos''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1428571428571428,
        fontSize: 14.0,
        fontFamily: 'Calibri',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
