import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedLogin/GeneratedRectangle4Widget11.dart';
import 'package:flutterapp/ui/widgets/generatedLogin/Generated123456deverdadWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedLogin/GeneratedClaveWidget1.dart';

/* Frame Group 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup25Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -0.8695652484893799,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.869564056396484,
              child: GeneratedRectangle4Widget11(),
            ),
            Positioned(
              left: 24.0,
              top: -13.043478012084961,
              right: null,
              bottom: null,
              width: 55.0,
              height: 18.04347801208496,
              child: GeneratedClaveWidget1(),
            ),
            Positioned(
              left: 14.0,
              top: 12.17391300201416,
              right: null,
              bottom: null,
              width: 225.0,
              height: 15.913043022155762,
              child: Generated123456deverdadWidget1(),
            )
          ]),
    );
  }
}
