import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedLogin/GeneratedNombreuninorteeducoWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedLogin/GeneratedRectangle4Widget12.dart';
import 'package:flutterapp/ui/widgets/generatedLogin/GeneratedCorreoWidget1.dart';

/* Frame Group 24
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup24Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -0.9230982661247253,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.61539077758789,
              child: GeneratedRectangle4Widget12(),
            ),
            Positioned(
              left: 25.0,
              top: -12.17391300201416,
              right: null,
              bottom: null,
              width: 80.54217529296875,
              height: 17.923076629638672,
              child: GeneratedCorreoWidget1(),
            ),
            Positioned(
              left: 14.0,
              top: 12.17391300201416,
              right: null,
              bottom: null,
              width: 228.0,
              height: 18.91304302215576,
              child: GeneratedNombreuninorteeducoWidget1(),
            )
          ]),
    );
  }
}
