import 'package:flutter/material.dart';

/* Rectangle Charged Battery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChargedBatteryWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.0,
      height: 15.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2dddb18383b50362b3205f1d88358c71778b9264.png",
          color: null,
          fit: BoxFit.contain,
          width: 15.0,
          height: 15.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
