import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedCardWidget7.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAvatarWidget8.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedCardWidget8.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAvatarWidget6.dart';

/* Frame Frame 69
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame69Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 686.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 334.0,
                    height: 197.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 1.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 196.0,
                            child: GeneratedCardWidget7(),
                          ),
                          Positioned(
                            left: 16.0,
                            top: 137.0,
                            right: null,
                            bottom: null,
                            width: 38.0,
                            height: 38.0,
                            child: GeneratedAvatarWidget6(),
                          ),
                          Positioned(
                            left: 359.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 196.0,
                            child: GeneratedCardWidget8(),
                          ),
                          Positioned(
                            left: 375.0,
                            top: 136.0,
                            right: null,
                            bottom: null,
                            width: 38.0,
                            height: 38.0,
                            child: GeneratedAvatarWidget8(),
                          )
                        ]),
                  ))
            ])),
      );
    });
  }
}
