import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedEllipse10Widget5.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedUXWidget3.dart';

/* Group Group 83
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup83Widget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 20.89655113220215,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 20.89655113220215,
              child: GeneratedEllipse10Widget5(),
            ),
            Positioned(
              left: 4.0,
              top: 5.224110126495361,
              right: null,
              bottom: null,
              width: 21.0,
              height: 14.57758617401123,
              child: GeneratedUXWidget3(),
            )
          ]),
    );
  }
}
