import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedSeeAllWidget3.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedCombinedShapeWidget3.dart';

/* Instance Component/Link
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponentLinkWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 68.0,
      height: 15.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(5.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 42.0,
              height: 17.0,
              child: GeneratedSeeAllWidget3(),
            ),
            Positioned(
              left: 56.0,
              top: 12.426908493041992,
              right: null,
              bottom: null,
              width: 9.853816986083984,
              height: 12.0,
              child: GeneratedCombinedShapeWidget3(),
            )
          ]),
    );
  }
}
