import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedEllipse67Widget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedChatWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedInicioWidget.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedSettingsWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRedWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedChatWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedPlaceMarkerWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAjustesWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedEllipse68Widget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedPersonatHomeWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedEditarWidget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedPlusWidget.dart';

/* Group Group 183
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup183Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.00,
        c: 0.00,
        d: 1.00,
        child: Container(
          width: 333.0,
          height: 42.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 333.0,
                  height: 42.0,
                  child: GeneratedRectangle6Widget(),
                ),
                Positioned(
                  left: 275.0,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 27.5966854095459,
                  height: 20.0,
                  child: GeneratedSettingsWidget(),
                ),
                Positioned(
                  left: 219.8536376953125,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 15.638121604919434,
                  height: 20.0,
                  child: GeneratedChatWidget(),
                ),
                Positioned(
                  left: 149.94198608398438,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 21.237567901611328,
                  height: 21.0,
                  child: GeneratedPlusWidget(),
                ),
                Positioned(
                  left: 83.70992279052734,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 27.5966854095459,
                  height: 20.0,
                  child: GeneratedPlaceMarkerWidget(),
                ),
                Positioned(
                  left: 148.10218811035156,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedEditarWidget(),
                ),
                Positioned(
                  left: 260.0,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 63.872928619384766,
                  height: 18.0,
                  child: GeneratedAjustesWidget(),
                ),
                Positioned(
                  left: 215.25408935546875,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedChatWidget1(),
                ),
                Positioned(
                  left: 83.70992279052734,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedRedWidget(),
                ),
                Positioned(
                  left: 19.317646026611328,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedInicioWidget(),
                ),
                Positioned(
                  left: 102.10772705078125,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 7.359116077423096,
                  height: 7.0,
                  child: GeneratedEllipse67Widget(),
                ),
                Positioned(
                  left: 230.89227294921875,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 7.359116077423096,
                  height: 7.0,
                  child: GeneratedEllipse68Widget(),
                ),
                Positioned(
                  left: 17.47785186767578,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 27.5966854095459,
                  height: 20.0,
                  child: GeneratedPersonatHomeWidget(),
                )
              ]),
        ));
  }
}
