import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedGroup83Widget.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedIconWidget5.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedUXDesignWidget.dart';

/* Group Group 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup85Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 281.6067810058594,
      height: 156.9952392578125,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 262.0,
              top: 132.9952392578125,
              right: null,
              bottom: null,
              width: 19.606779098510742,
              height: 24.0,
              child: GeneratedIconWidget5(),
            ),
            Positioned(
              left: 32.0,
              top: 2.8134210109710693,
              right: null,
              bottom: null,
              width: 52.0,
              height: 20.7559814453125,
              child: GeneratedUXDesignWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 22.507177352905273,
              child: GeneratedGroup83Widget(),
            )
          ]),
    );
  }
}
