import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse10Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 22.507177352905273,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M24 11.2536C24 17.4688 18.6274 22.5072 12 22.5072C5.37258 22.5072 0 17.4688 0 11.2536C0 5.0384 5.37258 0 12 0C18.6274 0 24 5.0384 24 11.2536Z')
          ..color = Color.fromARGB(255, 249, 58, 0),
      ]),
    );
  }
}
