import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRectangleWidget2.dart';

/* Group Tabs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTabsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 96.0,
      height: 37.35565185546875,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 96.0,
              height: 37.35565185546875,
              child: GeneratedRectangleWidget2(),
            )
          ]),
    );
  }
}
