import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse10Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 20.89655113220215,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M24 10.4483C24 16.2187 18.6274 20.8966 12 20.8966C5.37258 20.8966 0 16.2187 0 10.4483C0 4.67785 5.37258 0 12 0C18.6274 0 24 4.67785 24 10.4483Z')
          ..color = Color.fromARGB(255, 249, 58, 0),
      ]),
    );
  }
}
