import 'package:flutter/material.dart';

/* Rectangle Learning
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLearningWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.0,
      height: 20.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/df0b51fa9bc9cb220b3ff2d3379f593a089c03bb.png",
          color: null,
          fit: BoxFit.contain,
          width: 20.0,
          height: 20.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
