import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Text Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.00,
        c: -0.00,
        d: 1.00,
        child: Text(
          '''Inicio''',
          overflow: TextOverflow.visible,
          textAlign: TextAlign.center,
          style: TextStyle(
            height: 1.6,
            fontSize: 10.0,
            fontFamily: 'Calibri',
            fontWeight: FontWeight.w400,
            color: Color.fromARGB(255, 255, 255, 255),

            /* letterSpacing: 0.0, */
          ),
        ));
  }
}
