import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedGroup83Widget2.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedUIDesignWidget.dart';

/* Group Group 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup85Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 281.6067810058594,
      height: 159.61468505859375,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 32.0,
              top: 2.697253942489624,
              right: null,
              bottom: null,
              width: 49.0,
              height: 19.981651306152344,
              child: GeneratedUIDesignWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 281.6067810058594,
              height: 159.61468505859375,
              child: GeneratedGroup83Widget2(),
            )
          ]),
    );
  }
}
