import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Rectangle Plus +
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlusWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: 0.00,
        c: 0.00,
        d: 1.00,
        child: TransformHelper.translate(
            x: -0.50,
            y: -0.50,
            z: 0,
            child: Container(
              width: 21.237567901611328,
              height: 21.0,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(20.0),
                border: Border.all(
                  width: 1.0,
                  color: Color.fromARGB(255, 255, 204, 0),
                ),
                boxShadow: kIsWeb
                    ? []
                    : [
                        BoxShadow(
                          color: Color.fromARGB(63, 0, 0, 0),
                          offset: Offset(0.0, 4.0),
                          blurRadius: 4.0,
                        )
                      ],
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Image.asset(
                  "assets/images/de5123901371cd88d653b27b0b18c821b1622c7c.png",
                  color: null,
                  fit: BoxFit.contain,
                  width: 21.237567901611328,
                  height: 21.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
            )));
  }
}
