import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedInputsWidget1.dart';

/* Frame form-controls
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFormcontrolsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 310.0,
      height: 39.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 39.0,
              child: GeneratedInputsWidget1(),
            )
          ]),
    );
  }
}
