import 'package:flutter/material.dart';

/* Text ?123
    Autogenerated by FlutLab FTF Generator
  */
class Generated123Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''?123''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 13.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w500,
          color: Color.fromARGB(255, 127, 138, 142),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
