import 'package:flutter/material.dart';

/* Rectangle avatar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarWidget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 60.0,
      height: 60.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Image.asset(
          "assets/images/36ad3220367c6c81238faef47e06cb66ddcb031a.png",
          color: null,
          fit: BoxFit.cover,
          width: 60.0,
          height: 60.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
