import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedButtonWidget15.dart';

/* Frame media-option
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediaoptionWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 76.0,
          height: 39.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                Positioned(
                  left: 0.0,
                  top: 4.0,
                  right: null,
                  bottom: null,
                  width: 76.0,
                  height: 31.0,
                  child: GeneratedButtonWidget15(),
                )
              ]),
        ),
      ),
    );
  }
}
