import 'package:flutter/material.dart';

/* Text g
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''g''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 19.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 53, 64, 68),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
