import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMediaWidget6.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMediaWidget8.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMediaWidget5.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMediaWidget7.dart';

/* Frame user-list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserlistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 310.0,
      height: 335.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 60.0,
              child: GeneratedMediaWidget5(),
            ),
            Positioned(
              left: 0.0,
              top: 100.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 60.0,
              child: GeneratedMediaWidget6(),
            ),
            Positioned(
              left: 0.0,
              top: 175.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 60.0,
              child: GeneratedMediaWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 250.0,
              right: null,
              bottom: null,
              width: 310.0,
              height: 60.0,
              child: GeneratedMediaWidget8(),
            )
          ]),
    );
  }
}
