import 'package:flutter/material.dart';

/* Text SMALL
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSMALLWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''send''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 11.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.07999999821186066, */
      ),
    );
  }
}
