import 'package:flutter/material.dart';

/* Text LARGE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLARGEWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''conectar''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.171875,
          fontSize: 10.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 1.0800000429153442, */
        ),
      ),
    );
  }
}
