import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedEllipse65Widget7.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedEllipse66Widget7.dart';

/* Group home icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeiconWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.0,
      height: 20.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 3.0,
              top: 3.0,
              right: null,
              bottom: null,
              width: 14.0,
              height: 14.0,
              child: GeneratedEllipse65Widget7(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedEllipse66Widget7(),
            )
          ]),
    );
  }
}
