import 'package:flutter/material.dart';

/* Rectangle Place Marker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlaceMarkerWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLocationWidget'),
      child: Container(
        width: 27.0,
        height: 18.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/fc6a8c23d99e61f0bd5c33c9636a17419d874056.png",
            color: null,
            fit: BoxFit.contain,
            width: 27.0,
            height: 18.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
