import 'package:flutter/material.dart';

/* Rectangle Place Marker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlaceMarkerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 30.0,
      height: 20.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(0, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/0fc58fd1d50936f86882c00e3faac83c8bffb6a9.png",
          color: null,
          fit: BoxFit.contain,
          width: 30.0,
          height: 20.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
