import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 68
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse68Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.0,
      height: 7.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8 3.5C8 5.433 6.20914 7 4 7C1.79086 7 0 5.433 0 3.5C0 1.567 1.79086 0 4 0C6.20914 0 8 1.567 8 3.5Z')
          ..color = Color.fromARGB(255, 255, 217, 64),
      ]),
    );
  }
}
