import 'package:flutter/material.dart';

/* Text hace 2 horas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHace2horasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.bottomLeft,
      child: Text(
        '''hace 2 horas''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 2.8333333333333335,
          fontSize: 9.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 120, 133, 143),

          /* letterSpacing: 0.5, */
        ),
      ),
    );
  }
}
