import 'package:flutter/material.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedHomeiconWidget10.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedButtonWidget16.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedChargedBatteryWidget10.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedBackWidget11.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedWiFiWidget10.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedUserlistWidget.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedButtonWidget18.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedRecentsiconWidget10.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedSignalWidget10.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedHeadWidget5.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedFormcontrolsWidget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedRectangle12Widget2.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedButtonWidget17.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedButtonWidget19.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedLightAphabeticalWidget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/GeneratedHighFiveWidget.dart';
import 'package:flutterapp/perspective_newsapp/generatedconecwidget/generated/Generated942Widget10.dart';

/* Frame Conec
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConecWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1035.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1035.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(20.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(20.0),
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: null,
                                    right: null,
                                    bottom: 0.0,
                                    width: 362.0,
                                    height: 50.0,
                                    child: GeneratedRectangle12Widget2(),
                                  ),
                                  Positioned(
                                    left: 86.0,
                                    top: null,
                                    right: null,
                                    bottom: 1.0,
                                    width: 15.999999046325684,
                                    height: 16.0,
                                    child: GeneratedBackWidget11(),
                                  ),
                                  Positioned(
                                    left: 176.0,
                                    top: null,
                                    right: null,
                                    bottom: 15.0,
                                    width: 20.0,
                                    height: 20.0,
                                    child: GeneratedHomeiconWidget10(),
                                  ),
                                  Positioned(
                                    left: 271.0,
                                    top: null,
                                    right: null,
                                    bottom: 19.0,
                                    width: 12.0,
                                    height: 12.0,
                                    child: GeneratedRecentsiconWidget10(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 748.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 237.0,
                                    child: GeneratedLightAphabeticalWidget1(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 119.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 39.0,
                                    child: GeneratedFormcontrolsWidget1(),
                                  ),
                                  Positioned(
                                    left: 23.0,
                                    top: 152.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 335.0,
                                    child: GeneratedUserlistWidget(),
                                  ),
                                  Positioned(
                                    left: 10.0,
                                    top: 10.0,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 19.0,
                                    child: Generated942Widget10(),
                                  ),
                                  Positioned(
                                    left: 58.0,
                                    top: 75.0,
                                    right: null,
                                    bottom: null,
                                    width: 234.0,
                                    height: 22.0,
                                    child: GeneratedHeadWidget5(),
                                  ),
                                  Positioned(
                                    left: 284.0,
                                    top: 9.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 15.0,
                                    child: GeneratedSignalWidget10(),
                                  ),
                                  Positioned(
                                    left: 299.0,
                                    top: 9.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 15.0,
                                    child: GeneratedWiFiWidget10(),
                                  ),
                                  Positioned(
                                    left: 314.0,
                                    top: 9.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 15.0,
                                    child: GeneratedChargedBatteryWidget10(),
                                  ),
                                  Positioned(
                                    left: 307.0,
                                    top: 342.0,
                                    right: null,
                                    bottom: null,
                                    width: 23.0,
                                    height: 23.0,
                                    child: GeneratedHighFiveWidget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 248.0,
              top: 189.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 25.0,
              child: GeneratedButtonWidget16(),
            ),
            Positioned(
              left: 220.0,
              top: 338.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 25.0,
              child: GeneratedButtonWidget17(),
            ),
            Positioned(
              left: 246.0,
              top: 415.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 25.0,
              child: GeneratedButtonWidget18(),
            ),
            Positioned(
              left: 248.0,
              top: 264.0,
              right: null,
              bottom: null,
              width: 77.0,
              height: 25.0,
              child: GeneratedButtonWidget19(),
            )
          ]),
    ));
  }
}
