import 'package:flutter/material.dart';

/* Rectangle recents icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRecentsiconWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 12.0,
      height: 12.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(1.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(1.0),
        child: Container(
          color: Color.fromARGB(255, 196, 196, 196),
        ),
      ),
    );
  }
}
