import 'package:flutter/material.dart';

/* Rectangle Wi-Fi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWiFiWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.0,
      height: 15.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2af1645c0b55ff202a9f11e604a7bdcd225eeec0.png",
          color: null,
          fit: BoxFit.contain,
          width: 15.0,
          height: 15.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
