import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/mask/mask.dart';

/* Ellipse Avatar Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarProfileWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 48.0,
      height: 48.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: Mask.fromSVGPath(
                'M48 24C48 37.2548 37.2548 48 24 48C10.7452 48 0 37.2548 0 24C0 10.7452 10.7452 0 24 0C37.2548 0 48 10.7452 48 24Z',
                child: Image.asset(
                  "assets/images/7543702e0371f4907e15c6bc0d9def3eca68fac2.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 48.0,
                  height: 48.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
                offset: Offset(0.0, 0.0),
              ),
            )
          ]),
    );
  }
}
