import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChat/GeneratedLeftElementWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedChat/GeneratedRightElementWidget1.dart';

/* Instance List Cell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListCellWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 319.0,
        height: 56.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: null,
                width: 319.0,
                height: 56.0,
                child: GeneratedLeftElementWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: -56.0,
                bottom: null,
                width: 109.0,
                height: 56.0,
                child: GeneratedRightElementWidget1(),
              )
            ]),
      ),
    );
  }
}
