import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChat/GeneratedPlaceholderWidget.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Instance Inputs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 310.0,
      height: 39.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(50.0),
              child: Container(
                color: Color.fromARGB(255, 243, 243, 243),
              ),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 283.0,
              height: 20.0,
              child: TransformHelper.translate(
                  x: 2.50, y: 2.50, z: 0, child: GeneratedPlaceholderWidget()),
            )
          ]),
    );
  }
}
