import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedEllipse8Widget.dart';

/* Group Pin Active
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPinActiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 48.0,
      height: 61.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(40, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 8.0,
          )
        ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 61.0,
              child: GeneratedEllipse9Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedEllipse8Widget(),
            )
          ]),
    );
  }
}
