import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedTitleDescriptionWidget9.dart';

/* Instance Left Element
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeftElementWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 266.0,
      height: 70.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 123.0,
              height: 52.0,
              child: GeneratedTitleDescriptionWidget9(),
            )
          ]),
    );
  }
}
