import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedListCellWidget9.dart';

/* Frame List Avatar - Active
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListAvatarActiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 264.0,
      height: 80.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(45.0),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(40, 0, 0, 0),
            offset: Offset(0.0, 8.0),
            blurRadius: 16.0,
          )
        ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(45.0),
              child: Container(
                color: Color.fromARGB(255, 248, 210, 71),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 80.0,
              height: 80.0,
              child: GeneratedEllipse7Widget(),
            ),
            Positioned(
              left: 80.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 149.0,
              height: 70.0,
              child: GeneratedListCellWidget9(),
            )
          ]),
    );
  }
}
