import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedYesterdayWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedIconWidget28.dart';

/* Group Group 84
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup84Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 295.0,
      height: 24.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 271.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedIconWidget28(),
            ),
            Positioned(
              left: 0.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 184.0,
              height: 17.0,
              child: GeneratedYesterdayWidget2(),
            )
          ]),
    );
  }
}
