import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle5Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 41.0,
      height: 6.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0L38 0C39.6569 0 41 1.34315 41 3L41 3C41 4.65685 39.6569 6 38 6L0 6L0 0Z')
          ..color = Color.fromARGB(255, 255, 204, 0),
      ]),
    );
  }
}
