import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/mask/mask.dart';

/* BooleanOperation portada
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPortadaWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 103.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: Mask.fromSVGPath(
                'M360 0L0 0L0 103L125.267 103C125.09 101.191 125 99.356 125 97.5C125 66.8482 149.624 42 180 42C210.376 42 235 66.8482 235 97.5C235 99.356 234.91 101.191 234.733 103L360 103L360 0Z',
                child: Image.asset(
                  "assets/images/3bc8cc7a30b57c669997f0fe6cb1d54874a01f7f.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 103.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
                offset: Offset(0.0, 0.0),
              ),
            )
          ]),
    );
  }
}
