import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart' show kIsWeb;

/* Rectangle Rectangle 1950
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle1950Widget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.translate(
        x: -2.00,
        y: -2.00,
        z: 0,
        child: Container(
          width: 331.0,
          height: 206.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16.0),
            border: Border.all(
              width: 2.0,
              color: Color.fromARGB(255, 235, 239, 242),
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                kIsWeb
                    ? SizedBox.shrink()
                    : ClipRRect(
                        borderRadius: BorderRadius.circular(16.0),
                        child: SizedBox(
                            width: 331.0,
                            height: 206.0,
                            child: BackdropFilter(
                                filter: ui.ImageFilter.blur(
                                  sigmaX: 4.0,
                                  sigmaY: 4.0,
                                ),
                                child: Container(
                                    color: Colors.black.withOpacity(0.0)))),
                      ),
                ClipRRect(
                  borderRadius: BorderRadius.circular(16.0),
                  child: Container(
                    color: Color.fromARGB(153, 252, 253, 255),
                  ),
                )
              ]),
        ));
  }
}
