import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedGroupWidget3.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroupWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.0,
      height: 13.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 8.0,
              height: 13.0,
              child: GeneratedGroupWidget3(),
            )
          ]),
    );
  }
}
