import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/Generated17hoursagoWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedIconWidget27.dart';

/* Group Group 84
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup84Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 295.0,
      height: 20.89655113220215,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 271.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 20.89655113220215,
              child: GeneratedIconWidget27(),
            ),
            Positioned(
              left: 0.0,
              top: 5.22418737411499,
              right: null,
              bottom: null,
              width: 181.0,
              height: 12.448275566101074,
              child: Generated17hoursagoWidget2(),
            )
          ]),
    );
  }
}
