import 'package:flutter/material.dart';

/* Text Jane Cooper
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJaneCooperWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''Jane Cooper''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 18.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w700,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: -0.16500000655651093, */
        ),
      ),
    );
  }
}
