import 'package:flutter/material.dart';

/* Text When I was studying visual communications design in college, I was fascinated by how...
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas6
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''When I was studying visual communications design in college, I was fascinated by how...''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.4285714285714286,
          fontSize: 14.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
