import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* BooleanOperation Shift
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedShiftWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.320510864257812,
      height: 21.5,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8.66026 0L17.3205 9L11.6603 9L11.6603 14L5.66026 14L5.66026 9L0 9L8.66026 0ZM11.6603 21.5L11.6603 20L5.66026 20L5.66026 21.5L11.6603 21.5Z')
          ..color = Color.fromARGB(255, 127, 138, 142),
      ]),
    );
  }
}
