import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedEditEstado/GeneratedKeysWidget.dart';
import 'package:flutterapp/ui/widgets/generatedEditEstado/GeneratedBackgroundWidget.dart';

/* Component Light/Aphabetical
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLightAphabeticalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 237.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 237.0,
              child: GeneratedBackgroundWidget(),
            ),
            Positioned(
              left: 6.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 348.0,
              height: 206.0,
              child: GeneratedKeysWidget(),
            )
          ]),
    );
  }
}
