import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedEditEstado/GeneratedPepitaPerezdelosReyesWidget2.dart';

/* Frame media-content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediacontentWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 177.0,
        height: 22.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 24.0,
                child: GeneratedPepitaPerezdelosReyesWidget2(),
              )
            ]),
      ),
    );
  }
}
