import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedBackWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedButtonWidget8.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedHeadWidget3.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedChargedBatteryWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedHomeiconWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedSignalWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedRecentsiconWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedGroup24Widget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedWiFiWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedloginwidget/generated/GeneratedEndWidget5.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 640.0,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(20.0),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(20.0),
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.04444444179534912;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            15.999999046325684;

                        double percentHeight = 0.025;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 16.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX: constraints.maxWidth * 0.225,
                              translateY: constraints.maxHeight * 0.9734375,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedBackWidget6())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.05555555555555555;

                        final double height = constraints.maxHeight * 0.03125;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.475,
                              y: constraints.maxHeight * 0.9453125,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedHomeiconWidget6(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.03333333333333333;

                        final double height = constraints.maxHeight * 0.01875;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.7388888888888889,
                              y: constraints.maxHeight * 0.9515625,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedRecentsiconWidget6(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: -74.0,
                      top: -315.0,
                      right: null,
                      bottom: null,
                      width: 520.0,
                      height: 520.0,
                      child: GeneratedEllipse1Widget(),
                    ),
                    Positioned(
                      left: 72.0,
                      top: 112.0,
                      right: null,
                      bottom: null,
                      width: 234.0,
                      height: 24.0,
                      child: GeneratedHeadWidget3(),
                    ),
                    Positioned(
                      left: 108.0,
                      top: 445.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 17.0,
                      child: GeneratedEndWidget5(),
                    ),
                    Positioned(
                      left: 108.0,
                      top: 445.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 17.0,
                      child: TextButton(
                        onPressed: () {
                      Navigator.of(context).pushNamed(
                        '/GeneratedRegistWidget',
                      );
                    }),
                    ),
                    Positioned(
                      left: 150.0,
                      top: 487.0,
                      right: null,
                      bottom: null,
                      width: 72.0,
                      height: 70.0,
                      child: GeneratedImage1Widget1(),
                    ),
                    Positioned(
                      left: 278.0,
                      top: 10.0,
                      right: null,
                      bottom: null,
                      width: 15.0,
                      height: 15.0,
                      child: GeneratedSignalWidget6(),
                    ),
                    Positioned(
                      left: 301.0,
                      top: 10.0,
                      right: null,
                      bottom: null,
                      width: 15.0,
                      height: 15.0,
                      child: GeneratedWiFiWidget6(),
                    ),
                    Positioned(
                      left: 324.0,
                      top: 10.0,
                      right: null,
                      bottom: null,
                      width: 15.0,
                      height: 15.0,
                      child: GeneratedChargedBatteryWidget6(),
                    ),

                  ]),
            ),
            Positioned(
              left: 138.0,
              top: 382.0,
              right: null,
              bottom: null,
              width: 97.0,
              height: 36.0,
              child: GeneratedButtonWidget8(),
            ),
            Positioned(
              left: 44.0,
              top: 309.0,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.0,
              child: GeneratedGroup25Widget1(),
            ),
            Positioned(
              left: 44.0,
              top: 236.0,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.0,
              child: GeneratedGroup24Widget1(),
            )
          ]),
    ));
  }
}
