import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedLocation/GeneratedEllipse9Widget5.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Group Pin Active
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPinActiveWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 48.0,
      height: 61.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(40, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 8.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 61.0,
              child: GeneratedEllipse9Widget5(),
            )
          ]),
    );
  }
}
