import 'package:flutter/material.dart';

/* Rectangle avatar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarWidget61 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 47.0,
      height: 46.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Image.asset(
          "assets/images/b32b8e62322d5d8915818955c69bbc8edc18fa24.png",
          color: null,
          fit: BoxFit.cover,
          width: 47.0,
          height: 46.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
