import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedUXDesignWidget9.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedGroup83Widget12.dart';

/* Group Group 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup85Widget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 82.0,
      height: 24.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 32.0,
              top: 3.0,
              right: null,
              bottom: null,
              width: 52.0,
              height: 22.0,
              child: GeneratedUXDesignWidget9(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedGroup83Widget12(),
            )
          ]),
    );
  }
}
