import 'package:flutter/material.dart';

/* Text LLorem ipsum dolor sit amet, consectetur dipiscing elit, sed do eiusmod tempor incididunt.orem ipsum dolor sit amet.
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLLoremipsumdolorsitametconsecteturdipiscingelitseddoeiu1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''LLorem ipsum dolor sit amet, consectetur dipiscing elit, sed do eiusmod tempor incididunt.orem ipsum dolor sit amet.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.0,
        fontSize: 14.0,
        fontFamily: 'Calibri',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.5, */
      ),
    );
  }
}
