import 'package:flutter/material.dart';

/* Text 48 Conexiones
    Autogenerated by FlutLab FTF Generator
  */
class Generated48ConexionesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: RichText(
          overflow: TextOverflow.visible,
          textAlign: TextAlign.center,
          text: const TextSpan(
            style: TextStyle(
              height: 1.171875,
              fontSize: 12.0,
              fontFamily: 'Calibri',
              fontWeight: FontWeight.w700,
              color: Color.fromARGB(255, 125, 204, 228),

              /* letterSpacing: 0.0, */
            ),
            children: [
              TextSpan(
                text: '''48
''',
                style: TextStyle(
                  fontSize: 12.0,

                  /* letterSpacing: null, */
                ),
              ),
              TextSpan(
                text: '''Conexiones''',
                style: TextStyle(
                  fontSize: 12.0,
                  fontFamily: 'Calibri',
                  fontWeight: FontWeight.w300,
                  color: Color.fromARGB(255, 165, 165, 165),

                  /* letterSpacing: null, */
                ),
              )
            ],
          )),
    );
  }
}
