import 'package:flutter/material.dart';

/* Text 5 Seguidores
    Autogenerated by FlutLab FTF Generator
  */
class Generated5SeguidoresWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: RichText(
          overflow: TextOverflow.visible,
          textAlign: TextAlign.center,
          text: const TextSpan(
            style: TextStyle(
              height: 1.171875,
              fontSize: 12.0,
              fontFamily: 'Roboto',
              fontWeight: FontWeight.w400,
              color: Color.fromARGB(255, 0, 0, 0),

              /* letterSpacing: 0.0, */
            ),
            children: [
              TextSpan(
                text: '''5
''',
                style: TextStyle(
                  height: 1.171875,
                  fontSize: 12.0,
                  fontFamily: 'Calibri',
                  fontWeight: FontWeight.w700,
                  color: Color.fromARGB(255, 125, 204, 228),

                  /* letterSpacing: 0.0, */
                ),
              ),
              TextSpan(
                text: '''Seguidores''',
                style: TextStyle(
                  height: 1.171875,
                  fontSize: 12.0,
                  fontFamily: 'Calibri',
                  fontWeight: FontWeight.w300,
                  color: Color.fromARGB(255, 175, 175, 175),

                  /* letterSpacing: 0.0, */
                ),
              )
            ],
          )),
    );
  }
}
