import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedVectorWidget25.dart';

/* Frame Icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconWidget26 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 3.999999761581421,
                top: 11.00001049041748,
                right: null,
                bottom: null,
                width: 15.125,
                height: 1.125,
                child: GeneratedVectorWidget25(),
              )
            ]),
      ),
    );
  }
}
