import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedGroup84Widget8.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedImageWidget20.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget7.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedRectangle1950Widget19.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedGroup85Widget14.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget19 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 176.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 176.0,
              child: GeneratedRectangle1950Widget19(),
            ),
            Positioned(
              left: 211.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 100.0,
              child: GeneratedImageWidget20(),
            ),
            Positioned(
              left: 16.0,
              top: 48.0,
              right: null,
              bottom: null,
              width: 189.0,
              height: 74.0,
              child:
                  GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget7(),
            ),
            Positioned(
              left: 16.0,
              top: 136.0,
              right: null,
              bottom: null,
              width: 295.0,
              height: 24.0,
              child: GeneratedGroup84Widget8(),
            ),
            Positioned(
              left: 16.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 24.0,
              child: GeneratedGroup85Widget14(),
            )
          ]),
    );
  }
}
