import 'package:flutter/material.dart';

/* Text Is Your UI Messy? 7 Common Mistakes to Avoid
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIsYourUIMessy7CommonMistakestoAvoidWidget4
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''Is Your UI Messy? 7 Common Mistakes to Avoid''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.3333333333333333,
          fontSize: 18.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w700,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
