import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedUXDesignWidget10.dart';
import 'package:flutterapp/ui/widgets/generatedOtherP/GeneratedGroup83Widget13.dart';

/* Group Group 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup85Widget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 90.0,
      height: 20.89655113220215,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 32.0,
              top: 2.612077236175537,
              right: null,
              bottom: null,
              width: 60.0,
              height: 19.41379165649414,
              child: GeneratedUXDesignWidget10(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 20.89655113220215,
              child: GeneratedGroup83Widget13(),
            )
          ]),
    );
  }
}
