import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChat/GeneratedIconTitleWidget1.dart';

/* Instance Right Element
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRightElementWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: false,
      child: Container(
        width: 109.0,
        height: 56.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: null,
                top: null,
                right: 16.0,
                bottom: null,
                width: 77.0,
                height: 24.0,
                child: GeneratedIconTitleWidget1(),
              )
            ]),
      ),
    );
  }
}
