import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChat/GeneratedTitleDescriptionWidget1.dart';

/* Instance Left Element
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeftElementWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 319.0,
      height: 56.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 287.0,
              height: 38.0,
              child: GeneratedTitleDescriptionWidget1(),
            )
          ]),
    );
  }
}
