import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedTypehereWidget.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedVectorWidget5.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedGroup165Widget.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedGroup173Widget.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Group Group 166
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup166Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 343.0,
      height: 42.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 45.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 250.0,
              height: 41.0,
              child: GeneratedRectangle14Widget(),
            ),
            Positioned(
              left: 61.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 87.0,
              height: 23.0,
              child: GeneratedTypehereWidget(),
            ),
            Positioned(
              left: 302.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 41.0,
              height: 41.0,
              child: GeneratedGroup165Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 41.0,
              height: 41.0,
              child: GeneratedGroup173Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.061224489795918366;
                double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                double percentHeight = 0.5;
                double scaleY = (constraints.maxHeight * percentHeight) / 21.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7725947521865889,
                      translateY: constraints.maxHeight * 0.2857142857142857,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget5())
                ]);
              }),
            )
          ]),
    );
  }
}
