import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 275.0,
      height: 35.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.36508 6C4.36508 2.68629 7.05137 0 10.3651 0L269 0C272.314 0 275 2.68629 275 6L275 27.9394C275 31.2531 272.314 33.9394 269 33.9394L5.3351 33.9394L0 35L4.36508 29.697L4.36508 6Z')
          ..color = Color.fromARGB(255, 243, 243, 243),
      ]),
    );
  }
}
