import 'package:flutter/material.dart';

/* Rectangle Two messages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTwomessagesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 198.0,
      height: 125.0,
    );
  }
}
