import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/Generated1615Widget.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedRectangle15Widget4.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedGroup174Widget.dart';

/* Group Group 177
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup177Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 163.0,
      height: 104.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 163.0,
              height: 104.0,
              child: GeneratedRectangle15Widget4(),
            ),
            Positioned(
              left: 11.579235076904297,
              top: 8.64202880859375,
              right: null,
              bottom: null,
              width: 127.37158203125,
              height: 78.88257598876953,
              child: GeneratedGroup174Widget(),
            ),
            Positioned(
              left: 125.0,
              top: 79.0,
              right: null,
              bottom: null,
              width: 42.0,
              height: 20.0,
              child: Generated1615Widget(),
            )
          ]),
    );
  }
}
