import 'package:flutter/material.dart';

/* Text 16:17
    Autogenerated by FlutLab FTF Generator
  */
class Generated1617Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''16:17''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.171875,
          fontSize: 12.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 136, 128, 160),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
