import 'package:flutter/material.dart';

/* Text Hii.. I finally found a job!
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHiiIfinallyfoundajobWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''Hii.. I finally found a job!''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.171875,
          fontSize: 16.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
