import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 0.84,
        b: -0.54,
        c: 0.54,
        d: 0.84,
        child: Container(
          width: 10.678009033203125,
          height: 23.297475814819336,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M9.15258 4.99232L9.15258 17.4731C9.15258 19.7679 7.44105 21.6334 5.339 21.6334C3.23696 21.6334 1.52543 19.7679 1.52543 17.4731L1.52543 4.16026C1.52543 2.78405 2.55204 1.66411 3.81357 1.66411C5.07511 1.66411 6.10172 2.78405 6.10172 4.16026L6.10172 15.809C6.10172 16.2666 5.76002 16.6411 5.339 16.6411C4.91799 16.6411 4.57629 16.2666 4.57629 15.809L4.57629 4.99232L3.05086 4.99232L3.05086 15.809C3.05086 17.1852 4.07747 18.3052 5.339 18.3052C6.60053 18.3052 7.62715 17.1852 7.62715 15.809L7.62715 4.16026C7.62715 1.86713 5.91562 0 3.81357 0C1.71153 0 0 1.86713 0 4.16026L0 17.4731C0 20.6848 2.39492 23.2975 5.339 23.2975C8.28308 23.2975 10.678 20.6848 10.678 17.4731L10.678 4.99232L9.15258 4.99232Z')
              ..color = Color.fromARGB(40, 0, 0, 0),
          ]),
        ));
  }
}
