import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedCongratsAfterallthissearchesyoufinallymadeitWidget.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedImage117Widget.dart';

/* Group Group 174
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup174Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 127.37158203125,
      height: 78.88257598876953,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 129.37158203125,
              height: 80.88257598876953,
              child:
                  GeneratedCongratsAfterallthissearchesyoufinallymadeitWidget(),
            ),
            Positioned(
              left: 105.99442291259766,
              top: 39.630699157714844,
              right: null,
              bottom: null,
              width: 19.59562873840332,
              height: 19.090909957885742,
              child: GeneratedImage117Widget(),
            )
          ]),
    );
  }
}
