import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/Generated1612Widget.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedRectangle15Widget5.dart';
import 'package:flutterapp/ui/widgets/generatedChatInto/GeneratedHihannahowareyouWidget.dart';

/* Group Group 182
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup182Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 283.5,
      height: 35.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 283.5,
              height: 35.0,
              child: GeneratedRectangle15Widget5(),
            ),
            Positioned(
              left: 242.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 19.0,
              child: Generated1612Widget(),
            ),
            Positioned(
              left: 16.0,
              top: 6.4241943359375,
              right: null,
              bottom: null,
              width: 182.0,
              height: 22.15151596069336,
              child: GeneratedHihannahowareyouWidget(),
            )
          ]),
    );
  }
}
