import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle15Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: -1.00,
        b: -0.00,
        c: -0.00,
        d: 1.00,
        child: Container(
          width: 321.0,
          height: 35.00002670288086,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.09524 5.99999C5.09524 2.68628 7.78153 0 11.0952 0L315 0C318.314 0 321 2.68629 321 6L321 27.9394C321 31.2531 318.314 33.9394 315 33.9394L6.22751 33.9394L0 35L5.09524 29.697L5.09524 5.99999Z')
              ..color = Color.fromARGB(255, 207, 236, 245),
          ]),
        ));
  }
}
