import 'package:flutter/material.dart';

/* Rectangle image 27
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage27Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.0,
      height: 18.030303955078125,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b770bf98b0809dcbfeebbed84af453a42917d06c.png",
          color: null,
          fit: BoxFit.cover,
          width: 17.0,
          height: 18.030303955078125,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
