import 'package:flutter/material.dart';

/* Text Nombre
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNombreWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Nombre''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 16.0,
        fontFamily: 'Calibri',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 74, 158, 191),

        /* letterSpacing: -0.16500000655651093, */
      ),
    );
  }
}
