import 'package:flutter/material.dart';

/* Text End
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEndWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RichText(
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        text: const TextSpan(
          style: TextStyle(
            height: 1.171875,
            fontSize: 12.0,
            fontFamily: 'Rounded Mplus 1c',
            fontWeight: FontWeight.w400,
            color: Color.fromARGB(255, 0, 0, 0),

            /* letterSpacing: -0.16500000655651093, */
          ),
          children: [
            TextSpan(
              text: '''Acepta''',
              style: TextStyle(
                fontSize: 12.0,
                fontFamily: 'Calibri',
                fontWeight: FontWeight.w300,
                color: Color.fromARGB(255, 0, 0, 0),

                /* letterSpacing: null, */
              ),
            ),
            TextSpan(
              text: ''' ''',
              style: TextStyle(
                fontSize: 12.0,
                fontFamily: 'Calibri',
                fontWeight: FontWeight.w400,
                color: Color.fromARGB(255, 125, 204, 228),

                /* letterSpacing: null, */
              ),
            ),
            TextSpan(
              text: '''Términos y Condiciones''',
              style: TextStyle(
                fontSize: 12.0,
                fontFamily: 'Calibri',
                fontWeight: FontWeight.w400,
                color: Color.fromARGB(255, 74, 158, 191),
                decoration: TextDecoration.underline,
                /* letterSpacing: null, */
              ),
            )
          ],
        ));
  }
}
