import 'package:flutter/material.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedSignalWidget7.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedWiFiWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedButtonWidget9.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedChargedBatteryWidget7.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/Generated942Widget7.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedRecentsiconWidget7.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedHomeiconWidget7.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedBackWidget7.dart';
import 'package:flutterapp/perspective_newsapp/generatedintrowwidget/generated/GeneratedImage1Widget2.dart';

/* Frame IntroW
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroWWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 360.0,
              height: 640.0,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(20.0),
              ),
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(20.0),
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 283.0,
                      top: 8.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 15.0,
                      child: GeneratedSignalWidget7(),
                    ),
                    Positioned(
                      left: 300.0,
                      top: 8.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 15.0,
                      child: GeneratedWiFiWidget7(),
                    ),
                    Positioned(
                      left: 319.0,
                      top: 8.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 15.0,
                      child: GeneratedChargedBatteryWidget7(),
                    ),
                    Positioned(
                      left: -82.0,
                      top: 348.0,
                      right: null,
                      bottom: null,
                      width: 520.0,
                      height: 520.0,
                      child: GeneratedEllipse1Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.04444444179534912;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            15.999999046325684;

                        double percentHeight = 0.025;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 16.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.21666666666666667,
                              translateY: constraints.maxHeight * 0.978125,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedBackWidget7())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.03333333333333333;

                        final double height = constraints.maxHeight * 0.01875;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.7305555555555555,
                              y: constraints.maxHeight * 0.95625,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedRecentsiconWidget7(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 97.0,
                      top: 72.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 154.0,
                      child: GeneratedImage1Widget2(),
                    ),
                    Positioned(
                      left: 10.0,
                      top: 10.0,
                      right: null,
                      bottom: null,
                      width: 52.0,
                      height: 19.0,
                      child: Generated942Widget7(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.05555555555555555;

                final double height = constraints.maxHeight * 0.03125;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.4666666666666667,
                      y: constraints.maxHeight * 0.95,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedHomeiconWidget7(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 130.0,
              top: 269.0,
              right: null,
              bottom: null,
              width: 162.0,
              height: 36.0,
              child: GeneratedButtonWidget9(),
            )
          ]),
    ));
  }
}
