import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedRightElementWidget9.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'package:flutterapp/ui/widgets/generatedRed/GeneratedLeftElementWidget9.dart';

/* Instance List Cell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListCellWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 149.0,
        height: 70.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: null,
                width: 266.0,
                height: 70.0,
                child: GeneratedLeftElementWidget9(),
              ),
              Positioned(
                left: null,
                top: null,
                right: -226.0,
                bottom: null,
                width: 109.0,
                height: 56.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -7.00,
                    z: 0,
                    child: GeneratedRightElementWidget9()),
              )
            ]),
      ),
    );
  }
}
