import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedLocation/GeneratedPlaceholderWidget1.dart';

/* Instance Inputs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 310.0,
      height: 39.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(50.0),
              child: Container(
                color: Color.fromARGB(255, 243, 243, 243),
              ),
            ),
            Positioned(
              left: 16.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 280.0,
              height: 17.0,
              child: GeneratedPlaceholderWidget1(),
            )
          ]),
    );
  }
}
