import 'package:flutter/material.dart';

/* Text ¿Sobre qué quieres hablar?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSobreququiereshablarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: RichText(
          overflow: TextOverflow.visible,
          textAlign: TextAlign.left,
          text: const TextSpan(
            style: TextStyle(
              height: 1.171875,
              fontSize: 10.0,
              fontFamily: 'Calibri',
              fontWeight: FontWeight.w700,
              color: Color.fromARGB(255, 215, 213, 223),

              /* letterSpacing: 1.0800000429153442, */
            ),
            children: [
              TextSpan(
                text: '''¿Sobre ''',
                style: TextStyle(
                  fontSize: 10.0,

                  /* letterSpacing: null, */
                ),
              ),
              TextSpan(
                text: '''qué quieres hablar?''',
                style: TextStyle(
                  fontSize: 10.0,

                  /* letterSpacing: null, */
                ),
              )
            ],
          )),
    );
  }
}
