import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Vector 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVector2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.5,
      height: 3.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.5,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M11.5 3L11.5 3.75L12.25 3.75L12.25 3L11.5 3ZM10.75 0L10.75 3L12.25 3L12.25 0L10.75 0ZM11.5 2.25L0 2.25L0 3.75L11.5 3.75L11.5 2.25Z')
          ..color = Color.fromARGB(255, 235, 239, 242),
      ]),
    );
  }
}
