import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedEditEstado/GeneratedLARGEWidget11.dart';

/* Instance Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 77.0,
      height: 25.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
        border: Border.all(
          width: 2.0,
          color: Color.fromARGB(255, 255, 255, 255),
        ),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(0, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 18.5,
              top: 6.5,
              right: null,
              bottom: null,
              width: 45.0,
              height: 17.0,
              child: GeneratedLARGEWidget11(),
            )
          ]),
    );
  }
}
