import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse10Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 21.57798194885254,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M24 10.789C24 16.7476 18.6274 21.578 12 21.578C5.37258 21.578 0 16.7476 0 10.789C0 4.8304 5.37258 0 12 0C18.6274 0 24 4.8304 24 10.789Z')
          ..color = Color.fromARGB(255, 30, 16, 255),
      ]),
    );
  }
}
