import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRectangleWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedEstadoWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedNewsWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedSelectionWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedArtculosWidget1.dart';

/* Group Tabs
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTabsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 289.0,
      height: 25.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 289.0,
              height: 25.0,
              child: GeneratedRectangleWidget1(),
            ),
            Positioned(
              left: 93.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 25.0,
              child: GeneratedSelectionWidget1(),
            ),
            Positioned(
              left: 30.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 44.0,
              height: 21.0,
              child: GeneratedEstadoWidget1(),
            ),
            Positioned(
              left: 128.064208984375,
              top: 4.422271728515625,
              right: null,
              bottom: null,
              width: 46.779815673828125,
              height: 19.15037441253662,
              child: GeneratedNewsWidget1(),
            ),
            Positioned(
              left: 211.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 61.311927795410156,
              height: 19.150402069091797,
              child: GeneratedArtculosWidget1(),
            )
          ]),
    );
  }
}
