import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedEllipse10Widget2.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedIconWidget7.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedUIWidget.dart';

/* Group Group 83
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup83Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 281.6067810058594,
      height: 159.61468505859375,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 262.0,
              top: 135.61468505859375,
              right: null,
              bottom: null,
              width: 19.606779098510742,
              height: 24.0,
              child: GeneratedIconWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 21.57798194885254,
              child: GeneratedEllipse10Widget2(),
            ),
            Positioned(
              left: 6.0,
              top: 5.394501686096191,
              right: null,
              bottom: null,
              width: 17.0,
              height: 14.889907836914062,
              child: GeneratedUIWidget(),
            )
          ]),
    );
  }
}
