import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAvatarWidget11.dart';

/* Frame avatar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 38.0,
      height: 38.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 38.0,
              child: GeneratedAvatarWidget11(),
            )
          ]),
    );
  }
}
