import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedGroup85Widget3.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRectangle1950Widget8.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedImageWidget8.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget4.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedMediacontentWidget8.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 196.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 196.0,
              child: GeneratedRectangle1950Widget8(),
            ),
            Positioned(
              left: 211.0,
              top: 14.385320663452148,
              right: null,
              bottom: null,
              width: 100.0,
              height: 89.90825653076172,
              child: GeneratedImageWidget8(),
            ),
            Positioned(
              left: 16.0,
              top: 43.15596389770508,
              right: null,
              bottom: null,
              width: 189.0,
              height: 66.73394775390625,
              child:
                  GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget4(),
            ),
            Positioned(
              left: 64.0,
              top: 137.5,
              right: null,
              bottom: null,
              width: 101.0,
              height: 38.0,
              child: GeneratedMediacontentWidget8(),
            ),
            Positioned(
              left: 16.0,
              top: 14.385320663452148,
              right: null,
              bottom: null,
              width: 281.6067810058594,
              height: 159.61468505859375,
              child: GeneratedGroup85Widget3(),
            )
          ]),
    );
  }
}
