import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAyerWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedAnnetteBlackWidget3.dart';

/* Frame media-content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediacontentWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 101.0,
        height: 38.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 19.0,
                child: GeneratedAnnetteBlackWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 23.0,
                child: GeneratedAyerWidget1(),
              )
            ]),
      ),
    );
  }
}
