import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRectangle1950Widget10.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedImageWidget10.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/Generated6visualdesignfundamentalsthatUXdesignersWidget3.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedGroup85Widget5.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedIconWidget10.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas3.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedMediacontentWidget10.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 238.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 331.0,
              height: 242.0,
              child: GeneratedRectangle1950Widget10(),
            ),
            Positioned(
              left: 211.0,
              top: 13.931074142456055,
              right: null,
              bottom: null,
              width: 102.0,
              height: 89.0689697265625,
              child: GeneratedImageWidget10(),
            ),
            Positioned(
              left: 16.0,
              top: 41.79310607910156,
              right: null,
              bottom: null,
              width: 181.0,
              height: 64.68965530395508,
              child: Generated6visualdesignfundamentalsthatUXdesignersWidget3(),
            ),
            Positioned(
              left: 16.0,
              top: 178.0,
              right: null,
              bottom: null,
              width: 297.0,
              height: 36.82758331298828,
              child:
                  GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas3(),
            ),
            Positioned(
              left: 16.0,
              top: 13.931074142456055,
              right: null,
              bottom: null,
              width: 90.0,
              height: 20.89655113220215,
              child: GeneratedGroup85Widget5(),
            ),
            Positioned(
              left: 278.0,
              top: 135.0,
              right: null,
              bottom: null,
              width: 19.606779098510742,
              height: 24.0,
              child: GeneratedIconWidget10(),
            ),
            Positioned(
              left: 64.0,
              top: 122.5,
              right: null,
              bottom: null,
              width: 101.0,
              height: 38.0,
              child: GeneratedMediacontentWidget10(),
            )
          ]),
    );
  }
}
