import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedMediacontentWidget6.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedRectangle1950Widget6.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedIsYourUIMessy7CommonMistakestoAvoidWidget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedImageWidget6.dart';
import 'package:flutterapp/ui/widgets/generatedNewsOther/GeneratedGroup85Widget1.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 196.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 196.0,
              child: GeneratedRectangle1950Widget6(),
            ),
            Positioned(
              left: 211.0,
              top: 15.00478458404541,
              right: null,
              bottom: null,
              width: 100.0,
              height: 93.7799072265625,
              child: GeneratedImageWidget6(),
            ),
            Positioned(
              left: 16.0,
              top: 45.01435470581055,
              right: null,
              bottom: null,
              width: 189.0,
              height: 69.52153015136719,
              child: GeneratedIsYourUIMessy7CommonMistakestoAvoidWidget1(),
            ),
            Positioned(
              left: 64.0,
              top: 135.5,
              right: null,
              bottom: null,
              width: 101.0,
              height: 38.0,
              child: GeneratedMediacontentWidget6(),
            ),
            Positioned(
              left: 16.0,
              top: 15.00478458404541,
              right: null,
              bottom: null,
              width: 281.6067810058594,
              height: 156.9952392578125,
              child: GeneratedGroup85Widget1(),
            )
          ]),
    );
  }
}
