import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Rectangle Person at Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPersonatHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.00,
        c: -0.00,
        d: 1.00,
        child: Container(
          width: 27.5966854095459,
          height: 20.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(20.0),
            child: Image.asset(
              "assets/images/256ab92828ea897c9ac89e839c6d843406bc0844.png",
              color: null,
              fit: BoxFit.contain,
              width: 27.5966854095459,
              height: 20.0,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
