import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedGroup1Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedPolygon2Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedRectangle6Widget3.dart';

/* Instance backspace
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBackspaceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.0,
      height: 15.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 6.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 14.0,
              height: 13.0,
              child: GeneratedRectangle6Widget3(),
            ),
            Positioned(
              left: 0.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 8.0,
              child: GeneratedPolygon2Widget(),
            ),
            Positioned(
              left: 9.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 7.0,
              height: 5.999999523162842,
              child: GeneratedGroup1Widget(),
            )
          ]),
    );
  }
}
