import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedGroup2Widget.dart';

/* Instance Back
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBackWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 25.0,
      height: 25.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedEllipse1Widget(),
            ),
            Positioned(
              left: 7.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 11.5,
              height: 7.0,
              child: GeneratedGroup2Widget(),
            )
          ]),
    );
  }
}
