import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedVector2Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedVector3Widget.dart';

/* Group Group 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.5,
      height: 7.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.5,
              right: null,
              bottom: null,
              width: 11.5,
              height: 3.0,
              child: GeneratedVector2Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 3.0,
              height: 7.0,
              child: GeneratedVector3Widget(),
            )
          ]),
    );
  }
}
