import 'package:flutter/material.dart';

/* Text Head
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHeadWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''News''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 25.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w700,
          color: Color.fromARGB(255, 74, 158, 191),

          /* letterSpacing: 1.0800000429153442, */
        ),
      ),
    );
  }
}
