import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedRectangle4Widget9.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedCategoraWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedUXDesignWidget8.dart';

/* Frame Group 29
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup29Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: -3.0,
              top: -0.6154019832611084,
              right: null,
              bottom: null,
              width: 285.0,
              height: 40.30769729614258,
              child: GeneratedRectangle4Widget9(),
            ),
            Positioned(
              left: 19.0,
              top: -12.173914909362793,
              right: null,
              bottom: null,
              width: 78.54217529296875,
              height: 17.92307758331299,
              child: GeneratedCategoraWidget(),
            ),
            Positioned(
              left: 14.0,
              top: 12.173914909362793,
              right: null,
              bottom: null,
              width: 225.0,
              height: 15.913046836853027,
              child: GeneratedUXDesignWidget8(),
            )
          ]),
    );
  }
}
