import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedRectangle7Widget1.dart';

/* Frame space
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSpaceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 129.0,
      height: 34.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 129.0,
              height: 34.0,
              child: GeneratedRectangle7Widget1(),
            )
          ]),
    );
  }
}
