import 'package:flutter/material.dart';

/* Text 6 visual design fundamentals that UX designers...
    Autogenerated by FlutLab FTF Generator
  */
class Generated6visualdesignfundamentalsthatUXdesignersWidget6
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''6 visual design fundamentals that UX designers...''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.2857142857142858,
          fontSize: 14.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
