import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedLine1Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedLine2Widget.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.0,
      height: 5.999999523162842,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 1.4210854715202004e-14,
              top: 0.0,
              right: null,
              bottom: null,
              width: 8.485281944274902,
              height: 1.5,
              child: GeneratedLine1Widget(),
            ),
            Positioned(
              left: 7.0,
              top: 2.842170943040401e-14,
              right: null,
              bottom: null,
              width: 8.485280990600586,
              height: 1.5,
              child: GeneratedLine2Widget(),
            )
          ]),
    );
  }
}
