import 'package:flutter/material.dart';

/* Text Web Development
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWebDevelopmentWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Credit card''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 120, 133, 143),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
