import 'package:flutter/material.dart';

/* Rectangle Rectangle 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle7Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 129.0,
      height: 34.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(3.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(3.0),
        child: Container(
          color: Color.fromARGB(255, 200, 205, 209),
        ),
      ),
    );
  }
}
