import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedFrankEstebanWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedWebDevelopmentWidget3.dart';

/* Instance media-content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediacontentWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 164.0,
        height: 35.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 20.0,
                child: GeneratedFrankEstebanWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 16.0,
                child: GeneratedWebDevelopmentWidget3(),
              )
            ]),
      ),
    );
  }
}
