import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedPWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedEWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedVWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedGWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedSpaceWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated5Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated1Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedNWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedQWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated2Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedAWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedUWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedOWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedHWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated123Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedSWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedKWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated6Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedBackspaceWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedFWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated7Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedZWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated0Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedLWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedIWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedWWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedEmojiWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedJWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedTWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedCWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated4Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedXWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated8Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedWidget3.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedShiftWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedDWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedYWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated9Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedBackWidget12.dart';
import 'package:flutterapp/ui/widgets/generatedConec/Generated3Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedRWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedBWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedWidget2.dart';

/* Frame Keys
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeysWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 348.0,
      height: 206.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated1Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedQWidget1(),
            ),
            Positioned(
              left: 17.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedAWidget1(),
            ),
            Positioned(
              left: 53.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedZWidget1(),
            ),
            Positioned(
              left: 35.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated2Widget1(),
            ),
            Positioned(
              left: 35.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedWWidget1(),
            ),
            Positioned(
              left: 52.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedSWidget1(),
            ),
            Positioned(
              left: 88.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedXWidget1(),
            ),
            Positioned(
              left: 70.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated3Widget1(),
            ),
            Positioned(
              left: 70.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedEWidget1(),
            ),
            Positioned(
              left: 87.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedDWidget1(),
            ),
            Positioned(
              left: 123.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedCWidget1(),
            ),
            Positioned(
              left: 105.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated4Widget1(),
            ),
            Positioned(
              left: 105.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedRWidget1(),
            ),
            Positioned(
              left: 122.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedFWidget1(),
            ),
            Positioned(
              left: 158.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedVWidget1(),
            ),
            Positioned(
              left: 140.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated5Widget1(),
            ),
            Positioned(
              left: 140.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedTWidget1(),
            ),
            Positioned(
              left: 157.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedGWidget1(),
            ),
            Positioned(
              left: 193.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedBWidget1(),
            ),
            Positioned(
              left: 175.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated6Widget1(),
            ),
            Positioned(
              left: 175.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedYWidget1(),
            ),
            Positioned(
              left: 192.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedHWidget1(),
            ),
            Positioned(
              left: 228.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedNWidget1(),
            ),
            Positioned(
              left: 210.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated7Widget1(),
            ),
            Positioned(
              left: 210.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedUWidget1(),
            ),
            Positioned(
              left: 227.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedJWidget1(),
            ),
            Positioned(
              left: 263.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedMWidget1(),
            ),
            Positioned(
              left: 245.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated8Widget1(),
            ),
            Positioned(
              left: 245.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedIWidget1(),
            ),
            Positioned(
              left: 262.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedKWidget1(),
            ),
            Positioned(
              left: 280.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated9Widget1(),
            ),
            Positioned(
              left: 280.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedOWidget1(),
            ),
            Positioned(
              left: 297.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedLWidget1(),
            ),
            Positioned(
              left: 315.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated0Widget1(),
            ),
            Positioned(
              left: 315.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedPWidget1(),
            ),
            Positioned(
              left: 18.339752197265625,
              top: 139.0,
              right: null,
              bottom: null,
              width: 17.320510864257812,
              height: 21.5,
              child: GeneratedShiftWidget2(),
            ),
            Positioned(
              left: 308.0,
              top: 138.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 15.0,
              child: GeneratedBackspaceWidget1(),
            ),
            Positioned(
              left: 123.0,
              top: 172.0,
              right: null,
              bottom: null,
              width: 129.0,
              height: 34.0,
              child: GeneratedSpaceWidget1(),
            ),
            Positioned(
              left: 263.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 31.0,
              height: 32.0,
              child: GeneratedWidget2(),
            ),
            Positioned(
              left: 50.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 31.0,
              height: 32.0,
              child: GeneratedWidget3(),
            ),
            Positioned(
              left: 9.0,
              top: 176.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 30.0,
              child: Generated123Widget1(),
            ),
            Positioned(
              left: 92.0,
              top: 181.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedEmojiWidget1(),
            ),
            Positioned(
              left: 307.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedBackWidget12(),
            )
          ]),
    );
  }
}
