import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMediaoptionWidget.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedMediabodyWidget5.dart';

/* Instance media
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediaWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 310.0,
        height: 60.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 60.0,
                child: GeneratedMediabodyWidget5(),
              ),
              Positioned(
                left: 234.0,
                top: 10.5,
                right: null,
                bottom: null,
                width: 76.0,
                height: 39.0,
                child: GeneratedMediaoptionWidget(),
              )
            ]),
      ),
    );
  }
}
