import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedConec/GeneratedSMALLWidget3.dart';

/* Instance Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 76.0,
      height: 31.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
        border: Border.all(
          width: 2.0,
          color: Color.fromARGB(255, 0, 0, 0),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 16.0,
              top: 9.0,
              right: null,
              bottom: null,
              width: 42.0,
              height: 18.0,
              child: GeneratedSMALLWidget3(),
            )
          ]),
    );
  }
}
