import 'package:flutter/material.dart';

/* Rectangle High Five
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHighFiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 23.0,
      height: 23.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2aeb685a3bc6dcb49f84bd6b1dd2d15512a19206.png",
          color: null,
          fit: BoxFit.contain,
          width: 23.0,
          height: 23.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
