import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedShiftWidget1.dart';

/* Instance Shift
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedShiftWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.320510864257812,
      height: 21.5,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 17.320510864257812,
              height: 21.5,
              child: GeneratedShiftWidget1(),
            )
          ]),
    );
  }
}
