import 'package:flutter/material.dart';

/* Rectangle Rectangle 1952
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle1952Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 293.0,
      height: 201.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
        border: Border.all(
          width: 1.0,
          color: Color.fromARGB(255, 74, 158, 191),
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          color: Color.fromARGB(255, 255, 255, 255),
        ),
      ),
    );
  }
}
