import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedSpaceWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated0Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated5Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedFWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated4Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedTWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedEmojiWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedBWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedMWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedIWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedOWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedBackWidget9.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedPWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedEWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedCWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedZWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedBackspaceWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated8Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedWWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedHWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedRWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated6Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedDWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedShiftWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedQWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedXWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedGWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated9Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedSWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedNWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedYWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedJWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedLWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated2Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated123Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedVWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated7Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated1Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated3Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedAWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedUWidget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedKWidget.dart';

/* Frame Keys
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeysWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 348.0,
      height: 206.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated1Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedQWidget(),
            ),
            Positioned(
              left: 17.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedAWidget(),
            ),
            Positioned(
              left: 53.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedZWidget(),
            ),
            Positioned(
              left: 35.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated2Widget(),
            ),
            Positioned(
              left: 35.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedWWidget(),
            ),
            Positioned(
              left: 52.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedSWidget(),
            ),
            Positioned(
              left: 88.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedXWidget(),
            ),
            Positioned(
              left: 70.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated3Widget(),
            ),
            Positioned(
              left: 70.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedEWidget(),
            ),
            Positioned(
              left: 87.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedDWidget(),
            ),
            Positioned(
              left: 123.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedCWidget(),
            ),
            Positioned(
              left: 105.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated4Widget(),
            ),
            Positioned(
              left: 105.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedRWidget(),
            ),
            Positioned(
              left: 122.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedFWidget(),
            ),
            Positioned(
              left: 158.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedVWidget(),
            ),
            Positioned(
              left: 140.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated5Widget(),
            ),
            Positioned(
              left: 140.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedTWidget(),
            ),
            Positioned(
              left: 157.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedGWidget(),
            ),
            Positioned(
              left: 193.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedBWidget(),
            ),
            Positioned(
              left: 175.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated6Widget(),
            ),
            Positioned(
              left: 175.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedYWidget(),
            ),
            Positioned(
              left: 192.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedHWidget(),
            ),
            Positioned(
              left: 228.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedNWidget(),
            ),
            Positioned(
              left: 210.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated7Widget(),
            ),
            Positioned(
              left: 210.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedUWidget(),
            ),
            Positioned(
              left: 227.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedJWidget(),
            ),
            Positioned(
              left: 263.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedMWidget(),
            ),
            Positioned(
              left: 245.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated8Widget(),
            ),
            Positioned(
              left: 245.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedIWidget(),
            ),
            Positioned(
              left: 262.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedKWidget(),
            ),
            Positioned(
              left: 280.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated9Widget(),
            ),
            Positioned(
              left: 280.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedOWidget(),
            ),
            Positioned(
              left: 297.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedLWidget(),
            ),
            Positioned(
              left: 315.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: Generated0Widget(),
            ),
            Positioned(
              left: 315.0,
              top: 42.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 41.0,
              child: GeneratedPWidget(),
            ),
            Positioned(
              left: 18.339752197265625,
              top: 139.0,
              right: null,
              bottom: null,
              width: 17.320510864257812,
              height: 21.5,
              child: GeneratedShiftWidget(),
            ),
            Positioned(
              left: 308.0,
              top: 138.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 15.0,
              child: GeneratedBackspaceWidget(),
            ),
            Positioned(
              left: 123.0,
              top: 172.0,
              right: null,
              bottom: null,
              width: 129.0,
              height: 34.0,
              child: GeneratedSpaceWidget(),
            ),
            Positioned(
              left: 263.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 31.0,
              height: 32.0,
              child: GeneratedWidget(),
            ),
            Positioned(
              left: 50.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 31.0,
              height: 32.0,
              child: GeneratedWidget1(),
            ),
            Positioned(
              left: 9.0,
              top: 176.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 30.0,
              child: Generated123Widget(),
            ),
            Positioned(
              left: 92.0,
              top: 181.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedEmojiWidget(),
            ),
            Positioned(
              left: 307.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedBackWidget9(),
            )
          ]),
    );
  }
}
