import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/Generated6visualdesignfundamentalsthatUXdesignersWidget6.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedRectangle4Widget8.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedTtuloWidget.dart';

/* Frame Group 28
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup28Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 64.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -1.3912694454193115,
              right: null,
              bottom: null,
              width: 285.0,
              height: 65.39128875732422,
              child: GeneratedRectangle4Widget8(),
            ),
            Positioned(
              left: 25.0,
              top: -15.0,
              right: null,
              bottom: null,
              width: 55.0,
              height: 25.869564056396484,
              child: GeneratedTtuloWidget(),
            ),
            Positioned(
              left: 14.0,
              top: 19.200000762939453,
              right: null,
              bottom: null,
              width: 258.0,
              height: 24.39999771118164,
              child: Generated6visualdesignfundamentalsthatUXdesignersWidget6(),
            )
          ]),
    );
  }
}
