import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedVector1Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedEllipse2Widget5.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/ui/widgets/generatedPublic/GeneratedEllipse4Widget1.dart';

/* Instance emoji
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmojiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.0,
      height: 15.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedEllipse2Widget5(),
            ),
            Positioned(
              left: 4.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 2.0,
              height: 2.0,
              child: GeneratedEllipse3Widget(),
            ),
            Positioned(
              left: 9.0,
              top: 5.0,
              right: null,
              bottom: null,
              width: 2.0,
              height: 2.0,
              child: GeneratedEllipse4Widget1(),
            ),
            Positioned(
              left: 4.0,
              top: 9.0,
              right: null,
              bottom: null,
              width: 7.0,
              height: 2.0,
              child: GeneratedVector1Widget(),
            )
          ]),
    );
  }
}
