import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Rectangle Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.00,
        c: -0.00,
        d: 1.00,
        child: Container(
          width: 15.638121604919434,
          height: 20.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
            boxShadow: kIsWeb
                ? []
                : [
                    BoxShadow(
                      color: Color.fromARGB(63, 0, 0, 0),
                      offset: Offset(0.0, 4.0),
                      blurRadius: 4.0,
                    )
                  ],
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(20.0),
            child: Image.asset(
              "assets/images/77a824f64a5f87c205ce8ea1cbbb19abdacf35cf.png",
              color: null,
              fit: BoxFit.contain,
              width: 15.638121604919434,
              height: 20.0,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
