import 'package:flutter/material.dart';

/* Text Anteriores
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnterioresWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Anteriores''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.0666666666666667,
        fontSize: 15.0,
        fontFamily: 'Calibri',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
