import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

import 'package:flutterapp/ui/widgets/generatedNews/GeneratedAjustesWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedInicioWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedChatWidget3.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedRedWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedEditarWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedPlaceMarkerWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedChatWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedEllipse67Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedPlusWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedEllipse68Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedPersonatHomeWidget1.dart';

/* Group Group 183
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup183Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.00,
        c: 0.00,
        d: 1.00,
        child: Container(
          width: 333.0,
          height: 42.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 333.0,
                  height: 42.0,
                  child: GeneratedRectangle6Widget1(),
                ),
                Positioned(
                  left: 275.0,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 27.5966854095459,
                  height: 20.0,
                  child: GeneratedSettingsWidget1(),
                ),
                Positioned(
                  left: 219.8536376953125,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 15.638121604919434,
                  height: 20.0,
                  child: GeneratedChatWidget2(),
                ),
                Positioned(
                  left: 149.94198608398438,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 21.237567901611328,
                  height: 21.0,
                  child: GeneratedPlusWidget1(),
                ),
                Positioned(
                  left: 83.70992279052734,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 27.5966854095459,
                  height: 20.0,
                  child: GeneratedPlaceMarkerWidget1(),
                ),
                Positioned(
                  left: 148.10218811035156,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedEditarWidget1(),
                ),
                Positioned(
                  left: 260.0,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 63.872928619384766,
                  height: 18.0,
                  child: GeneratedAjustesWidget1(),
                ),
                Positioned(
                  left: 215.25408935546875,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedChatWidget3(),
                ),
                Positioned(
                  left: 83.70992279052734,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedRedWidget1(),
                ),
                Positioned(
                  left: 19.317646026611328,
                  top: 26.0,
                  right: null,
                  bottom: null,
                  width: 30.756906509399414,
                  height: 18.0,
                  child: GeneratedInicioWidget1(),
                ),
                Positioned(
                  left: 102.10772705078125,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 7.359116077423096,
                  height: 7.0,
                  child: GeneratedEllipse67Widget1(),
                ),
                Positioned(
                  left: 230.89227294921875,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 7.359116077423096,
                  height: 7.0,
                  child: GeneratedEllipse68Widget1(),
                ),
                Positioned(
                  left: 17.47785186767578,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 27.5966854095459,
                  height: 20.0,
                  child: GeneratedPersonatHomeWidget1(),
                )
              ]),
        ));
  }
}
