import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedVectorWidget11.dart';

/* Frame Icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 24.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 3.999999761581421,
              top: 11.00001049041748,
              right: null,
              bottom: null,
              width: 15.125,
              height: 1.125,
              child: GeneratedVectorWidget11(),
            )
          ]),
    );
  }
}
