import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse10Widget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.18947410583496,
      height: 20.89655113220215,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M24.1895 10.4483C24.1895 16.2187 18.7745 20.8966 12.0947 20.8966C5.415 20.8966 0 16.2187 0 10.4483C0 4.67785 5.415 0 12.0947 0C18.7745 0 24.1895 4.67785 24.1895 10.4483Z')
          ..color = Color.fromARGB(255, 249, 58, 0),
      ]),
    );
  }
}
