import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse10Widget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.05868911743164,
      height: 21.10344696044922,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M24.0587 10.5517C24.0587 16.3793 18.673 21.1034 12.0293 21.1034C5.38572 21.1034 0 16.3793 0 10.5517C0 4.72417 5.38572 0 12.0293 0C18.673 0 24.0587 4.72417 24.0587 10.5517Z')
          ..color = Color.fromARGB(255, 249, 58, 0),
      ]),
    );
  }
}
