import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Rectangle Place Marker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlaceMarkerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: -0.00,
        c: -0.00,
        d: 1.00,
        child: Container(
          width: 27.5966854095459,
          height: 20.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
            boxShadow: kIsWeb
                ? []
                : [
                    BoxShadow(
                      color: Color.fromARGB(63, 0, 0, 0),
                      offset: Offset(0.0, 4.0),
                      blurRadius: 4.0,
                    )
                  ],
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(20.0),
            child: Image.asset(
              "assets/images/0fc58fd1d50936f86882c00e3faac83c8bffb6a9.png",
              color: null,
              fit: BoxFit.contain,
              width: 27.5966854095459,
              height: 20.0,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
