import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup83Widget11.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedUXDesignWidget7.dart';

/* Group Group 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup85Widget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 90.22015380859375,
      height: 21.10344696044922,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 32.078369140625,
              top: 2.6379146575927734,
              right: null,
              bottom: null,
              width: 60.14183044433594,
              height: 19.586204528808594,
              child: GeneratedUXDesignWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.05868911743164,
              height: 21.10344696044922,
              child: GeneratedGroup83Widget11(),
            )
          ]),
    );
  }
}
