import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup85Widget7.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedIsYourUIMessy7CommonMistakestoAvoidWidget3.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedRectangle1950Widget12.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedImageWidget12.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup84Widget1.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 176.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 176.0,
              child: GeneratedRectangle1950Widget12(),
            ),
            Positioned(
              left: 211.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 100.0,
              child: GeneratedImageWidget12(),
            ),
            Positioned(
              left: 16.0,
              top: 48.0,
              right: null,
              bottom: null,
              width: 189.0,
              height: 74.0,
              child: GeneratedIsYourUIMessy7CommonMistakestoAvoidWidget3(),
            ),
            Positioned(
              left: 16.0,
              top: 136.0,
              right: null,
              bottom: null,
              width: 295.0,
              height: 24.0,
              child: GeneratedGroup84Widget1(),
            ),
            Positioned(
              left: 16.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 82.0,
              height: 24.0,
              child: GeneratedGroup85Widget7(),
            )
          ]),
    );
  }
}
