import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedUXWidget6.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedEllipse10Widget10.dart';

/* Group Group 83
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup83Widget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.18947410583496,
      height: 20.89655113220215,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.18947410583496,
              height: 20.89655113220215,
              child: GeneratedEllipse10Widget10(),
            ),
            Positioned(
              left: 4.031638145446777,
              top: 5.2241058349609375,
              right: null,
              bottom: null,
              width: 21.12631607055664,
              height: 14.57758617401123,
              child: GeneratedUXWidget6(),
            )
          ]),
    );
  }
}
