import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle13Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 71.0,
      height: 6.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0L68 0C69.6569 0 71 1.34315 71 3L71 3C71 4.65685 69.6569 6 68 6L0 6L0 0Z')
          ..color = Color.fromARGB(255, 255, 204, 0),
      ]),
    );
  }
}
