import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedIconWidget16.dart';
import 'package:flutterapp/ui/widgets/generatedNews/Generated17hoursagoWidget1.dart';

/* Group Group 84
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup84Widget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 284.5080871582031,
      height: 21.10344696044922,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 269.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 15.508085250854492,
              height: 21.10344696044922,
              child: GeneratedIconWidget16(),
            ),
            Positioned(
              left: 0.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 117.66446685791016,
              height: 12.55172348022461,
              child: Generated17hoursagoWidget1(),
            )
          ]),
    );
  }
}
