import 'package:flutter/material.dart';

/* Rectangle Sort Left
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSortLeftWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 25.0,
      height: 25.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/797050d088d3b295a9fa2d48467a8c5b663e79d3.png",
          color: null,
          fit: BoxFit.contain,
          width: 25.0,
          height: 25.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
