import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedCardWidget15.dart';

/* Frame Frame 65
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame65Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 701.7995872497559,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 340.0,
                    height: 204.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: -2.5815773010253906,
                            top: -1.0,
                            right: null,
                            bottom: null,
                            width: 704.3811645507812,
                            height: 205.0,
                            child: GeneratedCardWidget15(),
                          )
                        ]),
                  ))
            ])),
      );
    });
  }
}
