import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedUXWidget5.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedEllipse10Widget7.dart';

/* Group Group 83
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup83Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 24.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedEllipse10Widget7(),
            ),
            Positioned(
              left: 4.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 21.0,
              height: 16.0,
              child: GeneratedUXWidget5(),
            )
          ]),
    );
  }
}
