import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedCardWidget11.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedCardWidget12.dart';

/* Frame Frame 67
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame67Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 683.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 327.0,
                    height: 176.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 356.0,
                            top: 1.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 176.0,
                            child: GeneratedCardWidget11(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 176.0,
                            child: GeneratedCardWidget12(),
                          )
                        ]),
                  ))
            ])),
      );
    });
  }
}
