import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedCardWidget14.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedCardWidget13.dart';

/* Frame Frame 66
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame66Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 689.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 328.0,
                    height: 179.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 362.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 176.0,
                            child: GeneratedCardWidget13(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 3.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 176.0,
                            child: GeneratedCardWidget14(),
                          )
                        ]),
                  ))
            ])),
      );
    });
  }
}
