import 'package:flutter/material.dart';

/* Text Yesterday
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedYesterdayWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''Yesterday''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.0,
          fontSize: 12.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 152, 155, 168),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
