import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup84Widget4.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedImageWidget15.dart';
import 'package:flutterapp/ui/widgets/generatedNews/Generated6visualdesignfundamentalsthatUXdesignersWidget4.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas4.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedRectangle1950Widget15.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup85Widget10.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedCardWidget16.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 704.3811645507812,
      height: 205.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 3.0,
              right: null,
              bottom: null,
              width: 333.5815734863281,
              height: 206.0,
              child: GeneratedRectangle1950Widget15(),
            ),
            Positioned(
              left: 212.665771484375,
              top: 16.931076049804688,
              right: null,
              bottom: null,
              width: 102.78947448730469,
              height: 89.0689697265625,
              child: GeneratedImageWidget15(),
            ),
            Positioned(
              left: 16.12631607055664,
              top: 44.79310607910156,
              right: null,
              bottom: null,
              width: 182.4131622314453,
              height: 64.68965530395508,
              child: Generated6visualdesignfundamentalsthatUXdesignersWidget4(),
            ),
            Positioned(
              left: 16.12631607055664,
              top: 114.00000762939453,
              right: null,
              bottom: null,
              width: 296.5140075683594,
              height: 21.10344696044922,
              child: GeneratedGroup84Widget4(),
            ),
            Positioned(
              left: 15.118419647216797,
              top: 142.31028747558594,
              right: null,
              bottom: null,
              width: 299.3289489746094,
              height: 36.82758331298828,
              child:
                  GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas4(),
            ),
            Positioned(
              left: 16.12631607055664,
              top: 16.931076049804688,
              right: null,
              bottom: null,
              width: 90.71052551269531,
              height: 20.89655113220215,
              child: GeneratedGroup85Widget10(),
            ),
            Positioned(
              left: 376.58154296875,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.79962158203125,
              height: 204.0,
              child: GeneratedCardWidget16(),
            )
          ]),
    );
  }
}
