import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedPepitaPerezdelosReyesWidget4.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedNombreWidget.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedRectangle4Widget1.dart';

/* Frame Group 29
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup29Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 282.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: -2.96842098236084,
              top: -0.9230942726135254,
              right: null,
              bottom: null,
              width: 282.0,
              height: 40.61539077758789,
              child: GeneratedRectangle4Widget1(),
            ),
            Positioned(
              left: 18.799999237060547,
              top: -12.173914909362793,
              right: null,
              bottom: null,
              width: 77.76805114746094,
              height: 17.92307758331299,
              child: GeneratedNombreWidget(),
            ),
            Positioned(
              left: 13.852631568908691,
              top: 12.173914909362793,
              right: null,
              bottom: null,
              width: 222.6526336669922,
              height: 15.913046836853027,
              child: GeneratedPepitaPerezdelosReyesWidget4(),
            )
          ]),
    );
  }
}
