import 'package:flutter/material.dart';

/* Rectangle Leadership
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeadershipWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 30.0,
      height: 30.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b1e74182d5c9aa91fe658735b239e4fcd8852fc6.png",
          color: null,
          fit: BoxFit.contain,
          width: 30.0,
          height: 30.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
