import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle4Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 285.0,
      height: 41.000003814697266,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M14.8091 0.124461L14.8154 0.624421L14.8091 0.124461ZM270.021 0.292001L270.02 0.792001L270.021 0.292001ZM284.5 15.292L284.5 26L285.5 26L285.5 15.292L284.5 15.292ZM270 40.5L15 40.5L15 41.5L270 41.5L270 40.5ZM0.5 26L0.5 15.1233L-0.5 15.1233L-0.5 26L0.5 26ZM14.8154 0.624421L24.5926 0.499959L24.5799 -0.499959L14.8027 -0.375498L14.8154 0.624421ZM61.4993 0.5L270.02 0.792001L270.022 -0.207998L61.5007 -0.5L61.4993 0.5ZM15 40.5C6.99187 40.5 0.5 34.0081 0.5 26L-0.5 26C-0.5 34.5604 6.43958 41.5 15 41.5L15 40.5ZM284.5 26C284.5 34.0081 278.008 40.5 270 40.5L270 41.5C278.56 41.5 285.5 34.5604 285.5 26L284.5 26ZM285.5 15.292C285.5 6.74005 278.574 -0.196023 270.022 -0.207998L270.02 0.792001C278.02 0.803204 284.5 7.29179 284.5 15.292L285.5 15.292ZM0.5 15.1233C0.5 7.18711 6.87993 0.725438 14.8154 0.624421L14.8027 -0.375498C6.31993 -0.267515 -0.5 6.63979 -0.5 15.1233L0.5 15.1233Z')
          ..color = Color.fromARGB(255, 74, 158, 191)
          ..setBlur(34.5),
      ]),
    );
  }
}
