import 'package:flutter/material.dart';

/* Rectangle avatar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAvatarWidget26 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100.0,
      height: 100.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Image.asset(
          "assets/images/8f4a1581a64a2b00fc6230fe79ac323e66894845.png",
          color: null,
          fit: BoxFit.cover,
          width: 100.0,
          height: 100.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
