import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedUXWidget8.dart';

/* Frame Frame 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 71.0,
      height: 17.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(20.0),
              child: Container(
                color: Color.fromARGB(255, 125, 204, 228),
              ),
            ),
            Positioned(
              left: 29.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 19.0,
              height: 20.0,
              child: GeneratedUXWidget8(),
            )
          ]),
    );
  }
}
