import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedCiudadWidget.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedUtilizatubicacinactualparaencontraramigoscercanosWidget.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedFilterEditWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/ui/widgets/generatedAjustes/GeneratedBarranquillaWidget1.dart';

/* Frame Group 34
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup34Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 282.0,
      height: 40.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: -1.0,
              right: null,
              bottom: null,
              width: 282.0,
              height: 41.0,
              child: GeneratedRectangle4Widget3(),
            ),
            Positioned(
              left: 27.0,
              top: -14.0,
              right: null,
              bottom: null,
              width: 54.70503616333008,
              height: 17.972972869873047,
              child: GeneratedCiudadWidget(),
            ),
            Positioned(
              left: 13.852630615234375,
              top: 12.173913955688477,
              right: null,
              bottom: null,
              width: 225.6526336669922,
              height: 18.913047790527344,
              child: GeneratedBarranquillaWidget1(),
            ),
            Positioned(
              left: 51.73381042480469,
              top: 53.0,
              right: null,
              bottom: null,
              width: 235.3093719482422,
              height: 16.0,
              child:
                  GeneratedUtilizatubicacinactualparaencontraramigoscercanosWidget(),
            ),
            Positioned(
              left: 254.0,
              top: 9.0,
              right: null,
              bottom: null,
              width: 20.0,
              height: 20.0,
              child: GeneratedFilterEditWidget2(),
            )
          ]),
    );
  }
}
