import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedEstados/GeneratedAvatarWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedEstados/GeneratedLLoremipsumdolorsitametconsecteturadipiscingelitseddoei1.dart';
import 'package:flutterapp/ui/widgets/generatedEstados/GeneratedMediacontentWidget1.dart';

/* Frame media-body
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediabodyWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 307.0,
      height: 38.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 38.0,
              child: GeneratedAvatarWidget2(),
            ),
            Positioned(
              left: 48.0,
              top: 2.5,
              right: null,
              bottom: null,
              width: 101.0,
              height: 33.0,
              child: GeneratedMediacontentWidget1(),
            ),
            Positioned(
              left: 159.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 154.0,
              height: 38.0,
              child:
                  GeneratedLLoremipsumdolorsitametconsecteturadipiscingelitseddoei1(),
            )
          ]),
    );
  }
}
