import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedEstados/GeneratedHace1horaWidget2.dart';
import 'package:flutterapp/ui/widgets/generatedEstados/GeneratedAnnetteBlackWidget2.dart';

/* Frame media-content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMediacontentWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 101.0,
        height: 33.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 14.0,
                child: GeneratedAnnetteBlackWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 20.0,
                child: GeneratedHace1horaWidget2(),
              )
            ]),
      ),
    );
  }
}
