import 'package:flutter/material.dart';

/* Rectangle Selection
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelectionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 103.66666412353516,
      height: 27.734649658203125,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(24.0),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(0, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(24.0),
        child: Container(
          color: Color.fromARGB(158, 42, 130, 169),
        ),
      ),
    );
  }
}
