import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPerfil/GeneratedArteWidget1.dart';

/* Frame Frame 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 71.0,
      height: 17.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(20.0),
              child: Container(
                color: Color(0xFF4A9EBF),
              ),
            ),
            Positioned(
              left: 26.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 26.0,
              height: 20.0,
              child: GeneratedArteWidget1(),
            )
          ]),
    );
  }
}
