import 'package:flutter/material.dart';

/* Text Barranquilla, Atlántico
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBarranquillaAtlnticoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Barranquilla, Atlántico''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Calibri',
        fontWeight: FontWeight.w300,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: -0.16500000655651093, */
      ),
    );
  }
}
