import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedPerfil/GeneratedLARGEWidget5.dart';

/* Instance Button
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 96.0,
      height: 36.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
        border: Border.all(
          width: 2.0,
          color: Color.fromARGB(255, 255, 204, 0),
        ),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(0, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 20.0,
              top: 9.0,
              right: null,
              bottom: null,
              width: 61.0,
              height: 23.0,
              child: GeneratedLARGEWidget5(),
            ),
            TextButton(
                    onPressed: () {
                      Navigator.of(context).pushNamed(
                        '/GeneratedLoginWidget',
                      );
                    })
          ]),
    );
  }
}
