import 'package:flutter/material.dart';

/* Text Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RichText(
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        text: const TextSpan(
          style: TextStyle(
            height: 1.171875,
            fontSize: 16.0,
            fontFamily: 'Calibri',
            fontWeight: FontWeight.w700,
            color: Color.fromARGB(255, 0, 0, 0),

            /* letterSpacing: -0.16500000655651093, */
          ),
          children: [
            TextSpan(
              text: '''Cuéntanos que te interesa,
''',
              style: TextStyle(
                fontSize: 15.0,
                fontFamily: 'Calibri',
                fontWeight: FontWeight.w300,
                color: Color.fromARGB(255, 255, 204, 0),

                /* letterSpacing: null, */
              ),
            ),
            TextSpan(
              text:
                  '''Selecciona por lo menos 3 categorías y así podremos hacer tú experiencia más interesante''',
              style: TextStyle(
                fontSize: 15.0,
                fontFamily: 'Calibri',
                fontWeight: FontWeight.w300,

                /* letterSpacing: null, */
              ),
            ),
            TextSpan(
              text: '''.''',
              style: TextStyle(
                fontSize: 15.0,

                /* letterSpacing: null, */
              ),
            )
          ],
        ));
  }
}
