import 'package:flutter/material.dart';

/* Text Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RichText(
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        text: const TextSpan(
          style: TextStyle(
            height: 1.171875,
            fontSize: 15.0,
            fontFamily: 'Calibri',
            fontWeight: FontWeight.w300,
            color: Color.fromARGB(255, 0, 0, 0),

            /* letterSpacing: -0.16500000655651093, */
          ),
          children: [
            TextSpan(
              text: '''Selecciona el''',
            ),
            TextSpan(
              text: ''' modo ''',
              style: TextStyle(
                color: Color.fromARGB(255, 255, 204, 0),

                /* letterSpacing: null, */
              ),
            )
          ],
        ));
  }
}
