import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle4Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 284.0,
      height: 38.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          2.0,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M14.8224 0.114581L14.8106 -0.885349L14.8224 0.114581ZM283 15.2901L283 23L285 23L285 15.2901L283 15.2901ZM269 37L15 37L15 39L269 39L269 37ZM1 23L1 15.1135L-1 15.1135L-1 23L1 23ZM14.8343 1.11451L24.5118 0.99993L24.4882 -0.99993L14.8106 -0.885349L14.8343 1.11451ZM76 1.29008L269 1.29008L269 -0.709924L76 -0.709924L76 1.29008ZM15 37C7.26802 37 1 30.732 1 23L-1 23C-1 31.8366 6.16345 39 15 39L15 37ZM283 23C283 30.732 276.732 37 269 37L269 39C277.837 39 285 31.8366 285 23L283 23ZM285 15.2901C285 6.45352 277.837 -0.709924 269 -0.709924L269 1.29008C276.732 1.29008 283 7.55809 283 15.2901L285 15.2901ZM1 15.1135C1 7.4462 7.16746 1.20528 14.8343 1.11451L14.8106 -0.885349C6.04852 -0.781607 -1 6.35086 -1 15.1135L1 15.1135Z')
          ..color = Color.fromARGB(255, 177, 224, 239)
          ..setBlur(34.5),
      ]),
    );
  }
}
