import 'package:flutter/material.dart';

/* Text Oscuro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOscuroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''Oscuro''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 12.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w300,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: -0.16500000655651093, */
        ),
      ),
    );
  }
}
