import 'package:flutter/material.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedWiFiWidget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedHomeiconWidget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame13Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedSettingsWidget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedTextWidget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedOscuroWidget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedBackWidget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedPlusWidget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedEndWidget3.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedRecentsiconWidget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedSignalWidget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedClaroWidget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedSunWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedAvatarWidget11.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedTabsWidget1.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedChargedBatteryWidget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedEndWidget2.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/Generated942Widget4.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedMoonandStarsWidget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedFrame10Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/perspective_newsapp/generatedperfilwidget/generated/GeneratedPlusWidget2.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1116.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1116.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(20.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(20.0),
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 271.0,
                                    right: null,
                                    bottom: null,
                                    width: 285.0,
                                    height: 40.0,
                                    child: GeneratedGroup28Widget(),
                                  ),
                                  Positioned(
                                    left: 39.0,
                                    top: 203.0,
                                    right: null,
                                    bottom: null,
                                    width: 285.0,
                                    height: 40.0,
                                    child: GeneratedGroup29Widget(),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 336.0,
                                    right: null,
                                    bottom: null,
                                    width: 278.0,
                                    height: 37.0,
                                    child: GeneratedGroup33Widget(),
                                  ),
                                  Positioned(
                                    left: 36.0,
                                    top: 395.0,
                                    right: null,
                                    bottom: null,
                                    width: 278.0,
                                    height: 37.0,
                                    child: GeneratedGroup34Widget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 457.0,
                                    right: null,
                                    bottom: null,
                                    width: 263.0,
                                    height: 86.0,
                                    child: GeneratedTextWidget(),
                                  ),
                                  Positioned(
                                    left: 39.0,
                                    top: 706.0,
                                    right: null,
                                    bottom: null,
                                    width: 263.0,
                                    height: 27.0,
                                    child: GeneratedTextWidget1(),
                                  ),
                                  Positioned(
                                    left: 39.0,
                                    top: 547.0,
                                    right: null,
                                    bottom: null,
                                    width: 97.0,
                                    height: 17.0,
                                    child: GeneratedFrame1Widget(),
                                  ),
                                  Positioned(
                                    left: 79.0,
                                    top: 745.0,
                                    right: null,
                                    bottom: null,
                                    width: 39.0,
                                    height: 20.0,
                                    child: GeneratedOscuroWidget(),
                                  ),
                                  Positioned(
                                    left: 244.0,
                                    top: 746.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 20.0,
                                    child: GeneratedClaroWidget(),
                                  ),
                                  Positioned(
                                    left: 39.0,
                                    top: 610.0,
                                    right: null,
                                    bottom: null,
                                    width: 97.0,
                                    height: 17.0,
                                    child: GeneratedFrame8Widget(),
                                  ),
                                  Positioned(
                                    left: 217.0,
                                    top: 578.0,
                                    right: null,
                                    bottom: null,
                                    width: 87.0,
                                    height: 17.0,
                                    child: GeneratedFrame6Widget(),
                                  ),
                                  Positioned(
                                    left: 217.0,
                                    top: 641.0,
                                    right: null,
                                    bottom: null,
                                    width: 87.0,
                                    height: 17.0,
                                    child: GeneratedFrame9Widget(),
                                  ),
                                  Positioned(
                                    left: 128.0,
                                    top: 578.0,
                                    right: null,
                                    bottom: null,
                                    width: 72.0,
                                    height: 17.0,
                                    child: GeneratedFrame4Widget(),
                                  ),
                                  Positioned(
                                    left: 128.0,
                                    top: 641.0,
                                    right: null,
                                    bottom: null,
                                    width: 72.0,
                                    height: 17.0,
                                    child: GeneratedFrame10Widget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 547.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 17.0,
                                    child: GeneratedFrame2Widget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 610.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 17.0,
                                    child: GeneratedFrame11Widget(),
                                  ),
                                  Positioned(
                                    left: 233.0,
                                    top: 546.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 17.0,
                                    child: GeneratedFrame7Widget(),
                                  ),
                                  Positioned(
                                    left: 233.0,
                                    top: 609.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 17.0,
                                    child: GeneratedFrame12Widget(),
                                  ),
                                  Positioned(
                                    left: 39.0,
                                    top: 578.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 17.0,
                                    child: GeneratedFrame5Widget(),
                                  ),
                                  Positioned(
                                    left: 39.0,
                                    top: 641.0,
                                    right: null,
                                    bottom: null,
                                    width: 71.0,
                                    height: 17.0,
                                    child: GeneratedFrame13Widget(),
                                  ),
                                  Positioned(
                                    left: 130.0,
                                    top: 968.0,
                                    right: null,
                                    bottom: null,
                                    width: 96.0,
                                    height: 36.0,
                                    child: GeneratedButtonWidget5(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 30.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 103.0,
                                    child: GeneratedRectangle5Widget(),
                                  ),
                                  Positioned(
                                    left: 130.0,
                                    top: 76.0,
                                    right: null,
                                    bottom: null,
                                    width: 100.0,
                                    height: 99.0,
                                    child: GeneratedEllipse4Widget(),
                                  ),
                                  Positioned(
                                    left: 130.0,
                                    top: 75.0,
                                    right: null,
                                    bottom: null,
                                    width: 100.0,
                                    height: 100.0,
                                    child: GeneratedAvatarWidget11(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.26666666666666666;

                                      final double height =
                                          constraints.maxHeight *
                                              0.033472806322104615;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.3638888888888889,
                                            y: constraints.maxHeight *
                                                0.6577060931899642,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: GeneratedTabsWidget1(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 195.0,
                                    top: 739.0,
                                    right: null,
                                    bottom: null,
                                    width: 28.0,
                                    height: 28.0,
                                    child: GeneratedEllipse5Widget(),
                                  ),
                                  Positioned(
                                    left: 140.2510986328125,
                                    top: 739.69775390625,
                                    right: null,
                                    bottom: null,
                                    width: 18.05348777770996,
                                    height: 23.24054527282715,
                                    child: GeneratedMoonandStarsWidget(),
                                  ),
                                  Positioned(
                                    left: 199.0,
                                    top: 740.0,
                                    right: null,
                                    bottom: null,
                                    width: 19.0,
                                    height: 25.0,
                                    child: GeneratedSunWidget(),
                                  ),
                                  Positioned(
                                    left: 208.0,
                                    top: 149.0,
                                    right: null,
                                    bottom: null,
                                    width: 23.0,
                                    height: 26.0,
                                    child: GeneratedPlusWidget1(),
                                  ),
                                  Positioned(
                                    left: 330.0,
                                    top: 125.0,
                                    right: null,
                                    bottom: null,
                                    width: 23.0,
                                    height: 26.0,
                                    child: GeneratedPlusWidget2(),
                                  ),
                                  Positioned(
                                    left: 126.0,
                                    top: 1018.0,
                                    right: null,
                                    bottom: null,
                                    width: 132.0,
                                    height: 17.0,
                                    child: GeneratedEndWidget2(),
                                  ),
                                  Positioned(
                                    left: 61.0,
                                    top: 821.0,
                                    right: null,
                                    bottom: null,
                                    width: 94.0,
                                    height: 91.0,
                                    child: GeneratedImage3Widget(),
                                  ),
                                  Positioned(
                                    left: 170.0,
                                    top: 820.0,
                                    right: null,
                                    bottom: null,
                                    width: 152.0,
                                    height: 47.0,
                                    child: GeneratedEndWidget3(),
                                  ),
                                  Positioned(
                                    left: 185.0,
                                    top: 874.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 29.0,
                                    child: GeneratedButtonWidget6(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: null,
                                    right: null,
                                    bottom: 0.0,
                                    width: 362.0,
                                    height: 50.0,
                                    child: GeneratedRectangle12Widget(),
                                  ),
                                  Positioned(
                                    left: 85.0,
                                    top: null,
                                    right: null,
                                    bottom: 1.0,
                                    width: 15.999999046325684,
                                    height: 16.0,
                                    child: GeneratedBackWidget4(),
                                  ),
                                  Positioned(
                                    left: 270.0,
                                    top: null,
                                    right: null,
                                    bottom: 19.0,
                                    width: 12.0,
                                    height: 12.0,
                                    child: GeneratedRecentsiconWidget4(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 30.0,
                                    child: GeneratedRectangle7Widget(),
                                  ),
                                  Positioned(
                                    left: 282.0,
                                    top: 8.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 15.0,
                                    child: GeneratedSignalWidget4(),
                                  ),
                                  Positioned(
                                    left: 299.0,
                                    top: 8.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 15.0,
                                    child: GeneratedWiFiWidget4(),
                                  ),
                                  Positioned(
                                    left: 318.0,
                                    top: 8.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 15.0,
                                    child: GeneratedChargedBatteryWidget4(),
                                  ),
                                  Positioned(
                                    left: 10.0,
                                    top: 10.0,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 19.0,
                                    child: Generated942Widget4(),
                                  ),
                                  Positioned(
                                    left: 101.0,
                                    top: 1013.0,
                                    right: null,
                                    bottom: null,
                                    width: 21.0,
                                    height: 26.0,
                                    child: GeneratedSettingsWidget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 175.0,
              top: null,
              right: null,
              bottom: 15.0,
              width: 20.0,
              height: 20.0,
              child: GeneratedHomeiconWidget4(),
            )
          ]),
    ));
  }
}
