import 'package:flutter/material.dart';

/* Rectangle Rectangle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 289.0,
      height: 25.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(32.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(32.0),
        child: Container(
          color: Color.fromARGB(255, 125, 204, 228),
        ),
      ),
    );
  }
}
