import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedCardWidget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedCardWidget1.dart';

/* Frame Frame 71
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame71Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Container(
            width: 694.0,
            child: Stack(children: [
              Container(
                  height: constraints.maxHeight,
                  child: Container(
                    width: 335.0,
                    height: 205.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 367.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 201.0,
                            child: GeneratedCardWidget(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 327.0,
                            height: 201.0,
                            child: GeneratedCardWidget1(),
                          )
                        ]),
                  ))
            ])),
      );
    });
  }
}
