import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedVectorWidget.dart';

/* Frame Icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 19.606779098510742,
        height: 24.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 3.267796277999878,
                top: 11.00001049041748,
                right: null,
                bottom: null,
                width: 12.356355667114258,
                height: 1.125,
                child: GeneratedVectorWidget(),
              )
            ]),
      ),
    );
  }
}
