import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedDeporteWidget1.dart';

/* Frame Frame 72
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame72Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 97.0,
      height: 25.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
        border: Border.all(
          width: 1.0,
          color: Color.fromARGB(255, 125, 204, 228),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(20.0),
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 25.0,
              top: 4.0,
              right: null,
              bottom: null,
              width: 51.0,
              height: 22.0,
              child: GeneratedDeporteWidget1(),
            )
          ]),
    );
  }
}
