import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedImageWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedMediacontentWidget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/Generated6visualdesignfundamentalsthatUXdesignersWidget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedRectangle1950Widget.dart';
import 'package:flutterapp/ui/widgets/generatedArtic/GeneratedIconWidget.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 201.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 331.0,
              height: 205.0,
              child: GeneratedRectangle1950Widget(),
            ),
            Positioned(
              left: 211.0,
              top: 13.931074142456055,
              right: null,
              bottom: null,
              width: 102.0,
              height: 89.0689697265625,
              child: GeneratedImageWidget(),
            ),
            Positioned(
              left: 16.0,
              top: 18.0,
              right: null,
              bottom: null,
              width: 181.0,
              height: 64.68965530395508,
              child: Generated6visualdesignfundamentalsthatUXdesignersWidget(),
            ),
            Positioned(
              left: 16.0,
              top: 143.0,
              right: null,
              bottom: null,
              width: 297.0,
              height: 36.82758331298828,
              child:
                  GeneratedWhenIwasstudyingvisualcommunicationsdesignincollegeIwas(),
            ),
            Positioned(
              left: 284.0,
              top: 105.0,
              right: null,
              bottom: null,
              width: 19.606779098510742,
              height: 24.0,
              child: GeneratedIconWidget(),
            ),
            Positioned(
              left: 16.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 101.0,
              height: 38.0,
              child: GeneratedMediacontentWidget(),
            )
          ]),
    );
  }
}
