import 'package:flutter/material.dart';

/* Text A new,revolutionary UI is just around the corner — here are...
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''A new,revolutionary UI is just around the corner — here are...''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.3333333333333333,
          fontSize: 18.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w700,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
