import 'package:flutter/material.dart';

/* Rectangle Image
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImageWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100.0,
      height: 100.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(8.0),
        child: Image.asset(
          "assets/images/70865a7557355fdf83e306c647a2d02ac7611682.png",
          color: null,
          fit: BoxFit.cover,
          width: 100.0,
          height: 100.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
