import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedUXDesignWidget6.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup83Widget10.dart';

/* Group Group 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup85Widget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 90.71052551269531,
      height: 20.89655113220215,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 32.252689361572266,
              top: 2.6120758056640625,
              right: null,
              bottom: null,
              width: 60.45789337158203,
              height: 19.41379165649414,
              child: GeneratedUXDesignWidget6(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.18947410583496,
              height: 20.89655113220215,
              child: GeneratedGroup83Widget10(),
            )
          ]),
    );
  }
}
