import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';

/* Rectangle Image
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImageWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.translate(
        x: -1.00,
        y: -1.00,
        z: 0,
        child: Container(
          width: 102.24453735351562,
          height: 89.93103790283203,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8.0),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(8.0),
            child: Image.asset(
              "assets/images/417fa006755196fa2454c38dd02dadc49a7a85e1.png",
              color: null,
              fit: BoxFit.cover,
              width: 102.24453735351562,
              height: 89.93103790283203,
              colorBlendMode: BlendMode.dstATop,
            ),
          ),
        ));
  }
}
