import 'package:flutter/material.dart';

/* Rectangle Rectangle 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle6Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 333.0,
      height: 42.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(32.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(32.0),
        child: Container(
          color: Color.fromARGB(127, 125, 204, 228),
        ),
      ),
    );
  }
}
