import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle12Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 101.0,
      height: 6.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0L98 0C99.6569 0 101 1.34315 101 3L101 3C101 4.65685 99.6569 6 98 6L0 6L0 0Z')
          ..color = Color.fromARGB(255, 255, 204, 0),
      ]),
    );
  }
}
