import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Vector Rectangle 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle5Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 29.0,
      height: 6.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0L26 0C27.6569 0 29 1.34315 29 3L29 3C29 4.65685 27.6569 6 26 6L0 6L0 0Z')
          ..color = Color.fromARGB(255, 255, 204, 0),
      ]),
    );
  }
}
