import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedRectangle1950Widget14.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup85Widget9.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget6.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedGroup84Widget3.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedImageWidget14.dart';

/* Group Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 327.0,
      height: 176.0,
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 176.0,
              child: GeneratedRectangle1950Widget14(),
            ),
            Positioned(
              left: 211.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 100.0,
              height: 100.0,
              child: GeneratedImageWidget14(),
            ),
            Positioned(
              left: 16.0,
              top: 48.0,
              right: null,
              bottom: null,
              width: 189.0,
              height: 74.0,
              child:
                  GeneratedAnewrevolutionaryUIisjustaroundthecornerhereareWidget6(),
            ),
            Positioned(
              left: 16.0,
              top: 136.0,
              right: null,
              bottom: null,
              width: 293.0,
              height: 24.0,
              child: GeneratedGroup84Widget3(),
            ),
            Positioned(
              left: 16.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 24.0,
              child: GeneratedGroup85Widget9(),
            )
          ]),
    );
  }
}
