import 'package:flutter/material.dart';

/* Rectangle Learning
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLearningWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.0,
      height: 20.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/e482a36c1ed90811614112faa8edf841e2513044.png",
          color: null,
          fit: BoxFit.contain,
          width: 20.0,
          height: 20.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
