import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/helpers/transform/transform.dart';
import 'package:flutterapp/ui/widgets/helpers/svg/svg.dart';

/* Ellipse Ellipse 68
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEllipse68Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TransformHelper.rotate(
        a: 1.00,
        b: 0.00,
        c: 0.00,
        d: 1.00,
        child: Container(
          width: 7.359116077423096,
          height: 7.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M7.35912 3.5C7.35912 5.433 5.71172 7 3.67956 7C1.64739 7 0 5.433 0 3.5C0 1.567 1.64739 0 3.67956 0C5.71172 0 7.35912 1.567 7.35912 3.5Z')
              ..color = Color.fromARGB(255, 255, 217, 64),
          ]),
        ));
  }
}
