import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedUXWidget7.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedEllipse10Widget11.dart';

/* Group Group 83
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup83Widget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.05868911743164,
      height: 21.10344696044922,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.05868911743164,
              height: 21.10344696044922,
              child: GeneratedEllipse10Widget11(),
            ),
            Positioned(
              left: 4.009765625,
              top: 5.275837421417236,
              right: null,
              bottom: null,
              width: 21.03912353515625,
              height: 14.67241382598877,
              child: GeneratedUXWidget7(),
            )
          ]),
    );
  }
}
