import 'package:flutter/material.dart';

/* Text Estado
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstadoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Text(
        '''Estado''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.1428571428571428,
          fontSize: 14.0,
          fontFamily: 'Calibri',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
