import 'package:flutter/material.dart';

/* Rectangle Leadership
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLeadershipWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedNewsOtherWidget'),
      child: Container(
        width: 21.0,
        height: 24.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/c5c028a9d31de10acd668b315e8aa8d4594cdb40.png",
            color: null,
            fit: BoxFit.contain,
            width: 21.0,
            height: 24.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
