import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedIconWidget15.dart';
import 'package:flutterapp/ui/widgets/generatedNews/Generated17hoursagoWidget.dart';

/* Group Group 84
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup84Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 296.5140075683594,
      height: 21.10344696044922,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 272.455322265625,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.05868911743164,
              height: 21.10344696044922,
              child: GeneratedIconWidget15(),
            ),
            Positioned(
              left: 0.0,
              top: 5.67242431640625,
              right: null,
              bottom: null,
              width: 182.4131622314453,
              height: 12.448275566101074,
              child: Generated17hoursagoWidget(),
            )
          ]),
    );
  }
}
