import 'package:flutter/material.dart';
import 'package:flutterapp/ui/widgets/generatedNews/GeneratedVectorWidget16.dart';

/* Frame Icon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedRectangle1950Widget15'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 15.508085250854492,
          height: 21.10344696044922,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                Positioned(
                  left: 2.584909439086914,
                  top: 9.672425270080566,
                  right: null,
                  bottom: null,
                  width: 9.773320198059082,
                  height: 0.9892234802246094,
                  child: GeneratedVectorWidget16(),
                )
              ]),
        ),
      ),
    );
  }
}
